// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MulletaFlix.Database.Implementations;

#nullable disable

namespace Jellyfin.Database.Implementations.Migrations
{
    [DbContext(typeof(MulletaFlixDbContext))]
    [Migration("20260706145845_AddBaseItemSeriesDateIndex")]
    partial class AddBaseItemSeriesDateIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.AccessSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<double>("EndHour")
                        .HasColumnType("double");

                    b.Property<double>("StartHour")
                        .HasColumnType("double");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccessSchedules");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("LogSeverity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Overview")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.Property<string>("ShortOverview")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.AncestorId", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("ItemId", "ParentItemId");

                    b.HasIndex("ParentItemId");

                    b.ToTable("AncestorIds");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.AttachmentStreamInfo", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Codec")
                        .HasColumnType("longtext");

                    b.Property<string>("CodecTag")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("Filename")
                        .HasColumnType("longtext");

                    b.Property<string>("MimeType")
                        .HasColumnType("longtext");

                    b.HasKey("ItemId", "Index");

                    b.ToTable("AttachmentStreamInfos");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Album")
                        .HasColumnType("longtext");

                    b.Property<string>("AlbumArtists")
                        .HasColumnType("longtext");

                    b.Property<string>("Artists")
                        .HasColumnType("longtext");

                    b.Property<int?>("Audio")
                        .HasColumnType("int");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CleanName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<float?>("CommunityRating")
                        .HasColumnType("float");

                    b.Property<float?>("CriticRating")
                        .HasColumnType("float");

                    b.Property<string>("CustomRating")
                        .HasColumnType("longtext");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateLastMediaAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateLastRefreshed")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateLastSaved")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EpisodeTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalSeriesId")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalServiceId")
                        .HasColumnType("longtext");

                    b.Property<int?>("ExtraType")
                        .HasColumnType("int");

                    b.Property<string>("ForcedSortName")
                        .HasColumnType("longtext");

                    b.Property<string>("Genres")
                        .HasColumnType("longtext");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("IndexNumber")
                        .HasColumnType("int");

                    b.Property<int?>("InheritedParentalRatingSubValue")
                        .HasColumnType("int");

                    b.Property<int?>("InheritedParentalRatingValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInMixedFolder")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMovie")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRepeat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSeries")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVirtualItem")
                        .HasColumnType("tinyint(1)");

                    b.Property<float?>("LUFS")
                        .HasColumnType("float");

                    b.Property<string>("MediaType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<float?>("NormalizationGain")
                        .HasColumnType("float");

                    b.Property<string>("OfficialRating")
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Overview")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ParentIndexNumber")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PreferredMetadataCountryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredMetadataLanguage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PremiereDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PresentationUniqueKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("PrimaryVersionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductionLocations")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<long?>("RunTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SeasonName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SeriesName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SeriesPresentationUniqueKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShowId")
                        .HasColumnType("longtext");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("SortName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Studios")
                        .HasColumnType("longtext");

                    b.Property<string>("Tagline")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TopParentId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("TotalBitrate")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnratedType")
                        .HasColumnType("longtext");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path");

                    b.HasIndex("PresentationUniqueKey");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SeriesName");

                    b.HasIndex("ExtraType", "OwnerId");

                    b.HasIndex("TopParentId", "Id");

                    b.HasIndex("Type", "CleanName");

                    b.HasIndex("TopParentId", "Type", "IsVirtualItem")
                        .HasFilter("\"PrimaryVersionId\" IS NULL AND (\"OwnerId\" IS NULL OR \"ExtraType\" IS NOT NULL)");

                    b.HasIndex("TopParentId", "Type", "IsVirtualItem", "SeriesId", "DateCreated");

                    b.HasIndex("Type", "TopParentId", "Id");

                    b.HasIndex("Type", "TopParentId", "PresentationUniqueKey");

                    b.HasIndex("Type", "TopParentId", "SortName");

                    b.HasIndex("Type", "TopParentId", "StartDate");

                    b.HasIndex("MediaType", "TopParentId", "IsVirtualItem", "PresentationUniqueKey");

                    b.HasIndex("TopParentId", "IsFolder", "IsVirtualItem", "DateCreated");

                    b.HasIndex("TopParentId", "MediaType", "IsVirtualItem", "DateCreated");

                    b.HasIndex("TopParentId", "Type", "IsVirtualItem", "DateCreated");

                    b.HasIndex("Type", "SeriesPresentationUniqueKey", "IsFolder", "IsVirtualItem");

                    b.HasIndex("Type", "SeriesPresentationUniqueKey", "ParentIndexNumber", "IndexNumber");

                    b.HasIndex("Type", "SeriesPresentationUniqueKey", "PresentationUniqueKey", "SortName");

                    b.HasIndex("IsFolder", "TopParentId", "IsVirtualItem", "PresentationUniqueKey", "DateCreated");

                    b.HasIndex("Type", "TopParentId", "IsVirtualItem", "PresentationUniqueKey", "DateCreated");

                    b.ToTable("BaseItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsFolder = false,
                            IsInMixedFolder = false,
                            IsLocked = false,
                            IsMovie = false,
                            IsRepeat = false,
                            IsSeries = false,
                            IsVirtualItem = false,
                            Name = "This is a placeholder item for UserData that has been detached from its original item",
                            Type = "PLACEHOLDER"
                        });
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemImageInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Blurhash")
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ImageType")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "ImageType");

                    b.ToTable("BaseItemImageInfos");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemMetadataField", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BaseItemMetadataFields");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemProvider", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProviderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderValue")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ItemId", "ProviderId");

                    b.HasIndex("ProviderId", "ItemId", "ProviderValue");

                    b.ToTable("BaseItemProviders");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemTrailerType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BaseItemTrailerTypes");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Chapter", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ChapterIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ImageDateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<long>("StartPositionTicks")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId", "ChapterIndex");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.CustomItemDisplayPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId", "Client", "Key")
                        .IsUnique();

                    b.ToTable("CustomItemDisplayPreferences");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.DiscountCoupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountFixed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("FirstPurchaseOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinPlanMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DiscountCoupons");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.DisplayPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChromecastVersion")
                        .HasColumnType("int");

                    b.Property<string>("Client")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DashboardTheme")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("EnableNextVideoInfoOverlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IndexBy")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ScrollDirection")
                        .HasColumnType("int");

                    b.Property<bool>("ShowBackdrop")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowSidebar")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SkipBackwardLength")
                        .HasColumnType("int");

                    b.Property<int>("SkipForwardLength")
                        .HasColumnType("int");

                    b.Property<string>("TvHome")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId", "Client")
                        .IsUnique();

                    b.ToTable("DisplayPreferences");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.HomeSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayPreferencesId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisplayPreferencesId");

                    b.ToTable("HomeSection");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.ImageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ImageInfos");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.ItemDisplayPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("IndexBy")
                        .HasColumnType("int");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("RememberIndexing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RememberSorting")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SortBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ViewType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ItemDisplayPreferences");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.ItemValue", b =>
                {
                    b.Property<Guid>("ItemValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CleanValue")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ItemValueId");

                    b.HasIndex("Type", "CleanValue");

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("ItemValues");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.ItemValueMap", b =>
                {
                    b.Property<Guid>("ItemValueId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("ItemValueId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemValuesMap");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.KeyframeData", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.PrimitiveCollection<string>("KeyframeTicks")
                        .HasColumnType("longtext");

                    b.Property<long>("TotalDuration")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId");

                    b.ToTable("KeyframeData");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.LinkedChildEntity", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ChildType")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId", "ChildType");

                    b.HasIndex("ParentId", "ChildType");

                    b.HasIndex("ParentId", "SortOrder");

                    b.ToTable("LinkedChildren", (string)null);
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.MediaSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("EndTicks")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SegmentProviderId")
                        .HasColumnType("longtext");

                    b.Property<long>("StartTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MediaSegments");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.MediaStreamInfo", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("int");

                    b.Property<string>("AspectRatio")
                        .HasColumnType("longtext");

                    b.Property<float?>("AverageFrameRate")
                        .HasColumnType("float");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("int");

                    b.Property<int?>("BitRate")
                        .HasColumnType("int");

                    b.Property<int?>("BlPresentFlag")
                        .HasColumnType("int");

                    b.Property<string>("ChannelLayout")
                        .HasColumnType("longtext");

                    b.Property<int?>("Channels")
                        .HasColumnType("int");

                    b.Property<string>("Codec")
                        .HasColumnType("longtext");

                    b.Property<string>("CodecTag")
                        .HasColumnType("longtext");

                    b.Property<string>("CodecTimeBase")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorPrimaries")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorSpace")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorTransfer")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int?>("DvBlSignalCompatibilityId")
                        .HasColumnType("int");

                    b.Property<int?>("DvLevel")
                        .HasColumnType("int");

                    b.Property<int?>("DvProfile")
                        .HasColumnType("int");

                    b.Property<int?>("DvVersionMajor")
                        .HasColumnType("int");

                    b.Property<int?>("DvVersionMinor")
                        .HasColumnType("int");

                    b.Property<int?>("ElPresentFlag")
                        .HasColumnType("int");

                    b.Property<bool?>("Hdr10PlusPresentFlag")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAnamorphic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsAvc")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForced")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsHearingImpaired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsInterlaced")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeyFrames")
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<float?>("Level")
                        .HasColumnType("float");

                    b.Property<string>("NalLengthSize")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("PixelFormat")
                        .HasColumnType("longtext");

                    b.Property<string>("Profile")
                        .HasColumnType("longtext");

                    b.Property<float?>("RealFrameRate")
                        .HasColumnType("float");

                    b.Property<int?>("RefFrames")
                        .HasColumnType("int");

                    b.Property<int?>("Rotation")
                        .HasColumnType("int");

                    b.Property<int?>("RpuPresentFlag")
                        .HasColumnType("int");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("int");

                    b.Property<int>("StreamType")
                        .HasColumnType("int");

                    b.Property<string>("TimeBase")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "StreamIndex");

                    b.ToTable("MediaStreamInfos");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.PaymentGatewayConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EnableCredit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableDebit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnablePix")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ExtraConfig")
                        .HasColumnType("longtext");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("SandboxMode")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GatewayName")
                        .IsUnique();

                    b.ToTable("PaymentGatewayConfigs");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("longtext");

                    b.Property<string>("GatewayTransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PricingPlanId")
                        .HasColumnType("int");

                    b.Property<string>("RecurringSubscriptionId")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("GatewayTransactionId")
                        .IsUnique();

                    b.HasIndex("PricingPlanId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.People", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PersonType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Peoples");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.PeopleBaseItemMap", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PeopleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ListOrder")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "PeopleId", "Role");

                    b.HasIndex("PeopleId");

                    b.HasIndex("ItemId", "ListOrder");

                    b.HasIndex("ItemId", "SortOrder");

                    b.ToTable("PeopleBaseItemMap");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Value")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasMaxLength(65535)
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.PricingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PricePerMonth")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DurationMonths")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("PricingPlans");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Security.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateLastActivity")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Security.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateLastActivity")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken", "DateLastActivity");

                    b.HasIndex("DeviceId", "DateLastActivity");

                    b.HasIndex("UserId", "DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Security.DeviceOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomName")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceOptions");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.TrickplayInfo", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("Bandwidth")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<int>("ThumbnailCount")
                        .HasColumnType("int");

                    b.Property<int>("TileHeight")
                        .HasColumnType("int");

                    b.Property<int>("TileWidth")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "Width");

                    b.ToTable("TrickplayInfos");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AudioLanguagePreference")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AuthenticationProviderId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CastReceiverId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("DisplayCollectionsView")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DisplayMissingEpisodes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableAutoLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableLocalPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableNextEpisodeAutoPlay")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableUserPreferenceAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HidePlayedInLatest")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("InternalId")
                        .HasColumnType("bigint");

                    b.Property<int>("InvalidLoginAttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LoginAttemptsBeforeLockout")
                        .HasColumnType("int");

                    b.Property<int>("MaxActiveSessions")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParentalRatingScore")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParentalRatingSubScore")
                        .HasColumnType("int");

                    b.Property<bool>("MustUpdatePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NormalizedUsername")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(65535)
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordResetProviderId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("PlayDefaultAudioTrack")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RememberAudioSelections")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RememberSubtitleSelections")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RemoteClientBitrateLimit")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int unsigned");

                    b.Property<string>("SubtitleLanguagePreference")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SubtitleMode")
                        .HasColumnType("int");

                    b.Property<int>("SyncPlayAccess")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.UserData", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomDataKey")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("AudioStreamIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastPlayedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Likes")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<long>("PlaybackPositionTicks")
                        .HasColumnType("bigint");

                    b.Property<bool>("Played")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Rating")
                        .HasColumnType("double");

                    b.Property<DateTime?>("RetentionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SubtitleStreamIndex")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "UserId", "CustomDataKey");

                    b.HasIndex("ItemId", "UserId", "IsFavorite");

                    b.HasIndex("ItemId", "UserId", "LastPlayedDate");

                    b.HasIndex("ItemId", "UserId", "PlaybackPositionTicks");

                    b.HasIndex("ItemId", "UserId", "Played");

                    b.HasIndex("UserId", "IsFavorite", "ItemId");

                    b.HasIndex("UserId", "ItemId", "LastPlayedDate");

                    b.HasIndex("UserId", "Played", "ItemId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.UserLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsUnlimited")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ExpirationDate");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserLicenses");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.AccessSchedule", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", null)
                        .WithMany("AccessSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.AncestorId", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Parents")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "ParentItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.AttachmentStreamInfo", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Owner")
                        .WithMany("Extras")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "DirectParent")
                        .WithMany("DirectChildren")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DirectParent");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemImageInfo", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemMetadataField", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("LockedFields")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemProvider", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Provider")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemTrailerType", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("TrailerTypes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Chapter", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Chapters")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.DisplayPreferences", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", null)
                        .WithMany("DisplayPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.HomeSection", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.DisplayPreferences", null)
                        .WithMany("HomeSections")
                        .HasForeignKey("DisplayPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.ImageInfo", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", null)
                        .WithOne("ProfileImage")
                        .HasForeignKey("MulletaFlix.Database.Implementations.Entities.ImageInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.ItemDisplayPreferences", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", null)
                        .WithMany("ItemDisplayPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.ItemValueMap", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("ItemValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulletaFlix.Database.Implementations.Entities.ItemValue", "ItemValue")
                        .WithMany("BaseItemsMap")
                        .HasForeignKey("ItemValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemValue");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.KeyframeData", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.LinkedChildEntity", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Child")
                        .WithMany("LinkedChildOfEntities")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Parent")
                        .WithMany("LinkedChildEntities")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.MediaStreamInfo", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("MediaStreams")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.DiscountCoupon", "Coupon")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MulletaFlix.Database.Implementations.Entities.PricingPlan", "PricingPlan")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("PricingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", "User")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("PricingPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.PeopleBaseItemMap", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("Peoples")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulletaFlix.Database.Implementations.Entities.People", "People")
                        .WithMany("BaseItems")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("People");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Permission", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Preference", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", null)
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.Security.Device", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.UserData", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", "Item")
                        .WithMany("UserData")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.UserLicense", b =>
                {
                    b.HasOne("MulletaFlix.Database.Implementations.Entities.User", "User")
                        .WithOne("License")
                        .HasForeignKey("MulletaFlix.Database.Implementations.Entities.UserLicense", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.BaseItemEntity", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Children");

                    b.Navigation("DirectChildren");

                    b.Navigation("Extras");

                    b.Navigation("Images");

                    b.Navigation("ItemValues");

                    b.Navigation("LinkedChildEntities");

                    b.Navigation("LinkedChildOfEntities");

                    b.Navigation("LockedFields");

                    b.Navigation("MediaStreams");

                    b.Navigation("Parents");

                    b.Navigation("Peoples");

                    b.Navigation("Provider");

                    b.Navigation("TrailerTypes");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.DiscountCoupon", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.DisplayPreferences", b =>
                {
                    b.Navigation("HomeSections");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.ItemValue", b =>
                {
                    b.Navigation("BaseItemsMap");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.People", b =>
                {
                    b.Navigation("BaseItems");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.PricingPlan", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("MulletaFlix.Database.Implementations.Entities.User", b =>
                {
                    b.Navigation("AccessSchedules");

                    b.Navigation("DisplayPreferences");

                    b.Navigation("ItemDisplayPreferences");

                    b.Navigation("License");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("Permissions");

                    b.Navigation("Preferences");

                    b.Navigation("ProfileImage");
                });
#pragma warning restore 612, 618
        }
    }
}
