-- Nebula bot token storage for Supabase/PostgreSQL.
CREATE TABLE IF NOT EXISTS public.nebula_bot_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index INTEGER NOT NULL,
    token TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_nebula_bot_tokens_index
    ON public.nebula_bot_tokens (index);

ALTER TABLE public.nebula_bot_tokens ENABLE ROW LEVEL SECURITY;

-- Backend access uses the Supabase secret key. No public read policy is created.
