// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace MediaBrowser.Providers.Plugins.MidiaStorageOnline
{
    internal static class MidiaStorageOnlineWorkbookLogoMappings
    {
        private static readonly Dictionary<string, string> _logos = new(StringComparer.OrdinalIgnoreCase)
        {
            ["animal planet"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/2018_Animal_Planet_logo.svg/960px-2018_Animal_Planet_logo.svg.png", // ANIMAL PLANET 4K -> AnimalPlanet.au (798)
            ["axn"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/AXN_logo_%282015%29.svg/960px-AXN_logo_%282015%29.svg.png", // AXN 4K -> AXN.br (1000)
            ["axn fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/AXN_logo_%282015%29.svg/960px-AXN_logo_%282015%29.svg.png", // AXN FHD² -> AXN.br (1000)
            ["axn hd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/AXN_logo_%282015%29.svg/960px-AXN_logo_%282015%29.svg.png", // AXN HD² -> AXN.br (1000)
            ["axn sd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/AXN_logo_%282015%29.svg/960px-AXN_logo_%282015%29.svg.png", // AXN SD² -> AXN.br (1000)
            ["band news"] = "https://i.ibb.co/0jVZBFp/u8ya-iw-R-400x400.jpg", // BAND NEWS FHD -> BandNews.br (798)
            ["band sports"] = "https://i.imgur.com/EuPvzJe.png", // BAND SPORTS FHD -> BandSports.br (798)
            ["canal brasil"] = "https://i.imgur.com/1MusQ5K.png", // CANAL BRASIL FHD -> CanalBrasil.br (798)
            ["canal brasil sd2"] = "https://i.imgur.com/1MusQ5K.png", // CANAL BRASIL SD² -> CanalBrasil.br (798)
            ["canal do boi"] = "https://i.imgur.com/pVM5MhS.png", // CANAL DO BOI FHD -> CanaldoBoi.br (798)
            ["canal futura"] = "https://i.imgur.com/LgynEBC.png", // CANAL FUTURA HD -> CanalFutura.br (798)
            ["canal rural"] = "https://i.imgur.com/NgIBbPX.png", // CANAL RURAL HD -> CanalRural.ar (798)
            ["cartoon network"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/960px-Cartoon_Network_2010_logo.svg.png", // CARTOON NETWORK FHD -> CartoonNetwork.au (798)
            ["cartoonito"] = "https://i.imgur.com/6vYWCD0.png", // CARTOONITO FHD -> Cartoonito.it (798)
            ["cnn brasil"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/CNN_Brasil.svg/960px-CNN_Brasil.svg.png", // CNN BRASIL 4K -> CNNBrasil.br (798)
            ["cnn brasil fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/CNN_Brasil.svg/960px-CNN_Brasil.svg.png", // CNN BRASIL FHD² -> CNNBrasil.br (798)
            ["cnn brasil money"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/CNN_Brasil.svg/960px-CNN_Brasil.svg.png", // CNN BRASIL MONEY FHD -> CNNBrasil.br (798)
            ["curta"] = "https://i.imgur.com/Rwrh0zU.png", // CURTA HD -> Curta.br (1000)
            ["discovery channel"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/2019_Discovery_logo.svg/960px-2019_Discovery_logo.svg.png", // DISCOVERY CHANNEL 4K -> DiscoveryChannel.au (798)
            ["discovery channel fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/2019_Discovery_logo.svg/960px-2019_Discovery_logo.svg.png", // DISCOVERY CHANNEL FHD² -> DiscoveryChannel.au (798)
            ["discovery channel hd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/2019_Discovery_logo.svg/960px-2019_Discovery_logo.svg.png", // DISCOVERY CHANNEL HD² -> DiscoveryChannel.au (798)
            ["discovery channel sd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/2019_Discovery_logo.svg/960px-2019_Discovery_logo.svg.png", // DISCOVERY CHANNEL SD² -> DiscoveryChannel.au (798)
            ["discovery kids"] = "https://i.imgur.com/2JPtmZR.png", // DISCOVERY KIDS FHD -> DiscoveryKids.au (798)
            ["discovery science"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Discovery_science_new_logo_2017.png/960px-Discovery_science_new_logo_2017.png", // DISCOVERY SCIENCE FHD -> DiscoveryScience.ca (798)
            ["discovery theater"] = "https://i.imgur.com/T07gvEb.png", // DISCOVERY THEATER FHD -> DiscoveryTheater.br (798)
            ["discovery theater fhd2"] = "https://i.imgur.com/T07gvEb.png", // DISCOVERY THEATER FHD² -> DiscoveryTheater.br (798)
            ["discovery theater hd2"] = "https://i.imgur.com/T07gvEb.png", // DISCOVERY THEATER HD² -> DiscoveryTheater.br (798)
            ["discovery turbo"] = "https://i.imgur.com/osCVMop.png", // DISCOVERY TURBO FHD -> DiscoveryTurbo.au (798)
            ["discovery world"] = "https://i.imgur.com/yNFmUkE.png", // DISCOVERY WORLD FHD -> DiscoveryWorld.us (798)
            ["fashion tv"] = "https://i.imgur.com/cZWKyuM.png", // FASHION TV FHD -> FashionTV.br (798)
            ["film arts"] = "https://i.imgur.com/ukdmEKD.png", // FILM & ARTS -> FilmArts.ar (798)
            ["food network"] = "https://upload.wikimedia.org/wikipedia/commons/0/06/Food_Network_logo.svg", // FOOD NETWORK FHD -> FoodNetwork.ca (798)
            ["food network fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/0/06/Food_Network_logo.svg", // FOOD NETWORK FHD² -> FoodNetwork.ca (798)
            ["food network hd2"] = "https://upload.wikimedia.org/wikipedia/commons/0/06/Food_Network_logo.svg", // FOOD NETWORK HD² -> FoodNetwork.ca (798)
            ["food network sd2"] = "https://upload.wikimedia.org/wikipedia/commons/0/06/Food_Network_logo.svg", // FOOD NETWORK SD² -> FoodNetwork.ca (798)
            ["globo news"] = "https://i.imgur.com/3yZyaCm.png", // GLOBO NEWS 4K -> GloboNews.br (798)
            ["globoplay novelas"] = "https://i.ibb.co/m5TBCDL2/Globoplay-Novelas-1.png", // GLOBOPLAY NOVELAS FHD -> GloboplayNovelas.br (798)
            ["gloob"] = "https://i.imgur.com/N1BUULh.png", // GLOOB FHD -> Gloob.br (1000)
            ["gloob fhd2"] = "https://i.imgur.com/N1BUULh.png", // GLOOB FHD² -> Gloob.br (1000)
            ["gloob hd2"] = "https://i.imgur.com/N1BUULh.png", // GLOOB HD² -> Gloob.br (1000)
            ["gloob sd2"] = "https://i.imgur.com/N1BUULh.png", // GLOOB SD² -> Gloob.br (1000)
            ["gloobinho"] = "https://i.imgur.com/UWkHErt.png", // GLOOBINHO FHD -> Gloobinho.br (798)
            ["gnt"] = "https://i.imgur.com/XymcvMy.png", // GNT 4K -> GNT.br (1000)
            ["gnt sd2"] = "https://i.imgur.com/XymcvMy.png", // GNT SD² -> GNT.br (1000)
            ["hbo 1"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/960px-HBO_logo.svg.png", // HBO 1 4K -> HBO.br (1000)
            ["hbo 1 fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/960px-HBO_logo.svg.png", // HBO 1 FHD² -> HBO.br (1000)
            ["hbo 1 hd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/960px-HBO_logo.svg.png", // HBO 1 HD² -> HBO.br (1000)
            ["hbo 1 sd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/960px-HBO_logo.svg.png", // HBO 1 SD² -> HBO.br (1000)
            ["hbo family"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/HBO_Family.svg/960px-HBO_Family.svg.png", // HBO FAMILY 4K -> HBOFamily.br (798)
            ["hbo mundi"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/HBO_Mundi.svg/960px-HBO_Mundi.svg.png", // HBO MUNDI FHD -> HBOMundi.br (798)
            ["hbo signature"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/HBO_Signature.svg/960px-HBO_Signature.svg.png", // HBO SIGNATURE FHD -> HBOSignature.br (798)
            ["hbo xtreme"] = "https://www.vertvcable.com/wp-content/uploads/2022/02/hboextreme.jpg", // HBO XTREME 4K -> HBOXtreme.br (798)
            ["investigation discovery"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/InvestigationDiscoveryLogo2020.svg/960px-InvestigationDiscoveryLogo2020.svg.png", // INVESTIGATION DISCOVERY FHD -> InvestigationDiscovery.au (798)
            ["jovem pan news"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Jovem_Pan_logo_2018.svg/960px-Jovem_Pan_logo_2018.svg.png", // JOVEM PAN NEWS FHD -> JovemPanNews.br (798)
            ["lifetime"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Logo_Lifetime_2020.svg/960px-Logo_Lifetime_2020.svg.png", // LIFETIME FHD -> Lifetime.ca (798)
            ["multishow"] = "https://i.imgur.com/bqVg8nT.png", // MULTISHOW 4K -> Multishow.br (798)
            ["multishow fhd2"] = "https://i.imgur.com/bqVg8nT.png", // MULTISHOW FHD² -> Multishow.br (798)
            ["multishow hd2"] = "https://i.imgur.com/bqVg8nT.png", // MULTISHOW HD² -> Multishow.br (798)
            ["multishow sd2"] = "https://i.imgur.com/bqVg8nT.png", // MULTISHOW SD² -> Multishow.br (798)
            ["music box"] = "https://i.imgur.com/3arWh0k.png", // MUSIC BOX FHD -> MusicBoxGold.ru (794)
            ["nba league pass 10"] = "https://upload.wikimedia.org/wikipedia/en/6/6e/NBA_League_Pass.png", // NBA LEAGUE PASS 10 HD -> NBALeaguePass10.us (798)
            ["nba league pass 11"] = "https://i.imgur.com/XhsI1e5.png", // NBA LEAGUE PASS 11 HD -> NBALeaguePass11.us (798)
            ["nba league pass 12"] = "https://i.imgur.com/1B1S3KJ.png", // NBA LEAGUE PASS 12 HD -> NBALeaguePass12.us (798)
            ["nhk world"] = "https://jiotvimages.cdn.jio.com/dare_images/images/NHK_World_Japan.png", // NHK WORLD HD -> NHKWorldJapan.jp (793)
            ["nickelodeon"] = "https://i.imgur.com/E84jnP8.png", // NICKELODEON FHD -> Nickelodeon.au (798)
            ["novo tempo"] = "https://i.imgur.com/5mSzvXt.png", // NOVO TEMPO FHD -> NovoTempoPortugal.pt (790)
            ["paramount"] = "https://i.imgur.com/Nki62R7.png", // PARAMOUNT FHD H265 -> ParamountComedy.ru (792)
            ["polishop"] = "https://i.imgur.com/gnfxeio.png", // POLISHOP HD -> Polishop.br (798)
            ["premiere 01 clubes"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 01 CLUBES FHD H265 -> Premiere10.br (796)
            ["premiere 02"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 02 FHD -> Premiere10.br (796)
            ["premiere 02 fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 02 FHD² -> Premiere10.br (796)
            ["premiere 02 hd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 02 HD² -> Premiere10.br (796)
            ["premiere 03"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 03 FHD -> Premiere10.br (796)
            ["premiere 03 fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 03 FHD² -> Premiere10.br (796)
            ["premiere 03 hd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 03 HD² -> Premiere10.br (796)
            ["premiere 04"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 04 FHD -> Premiere10.br (796)
            ["premiere 04 fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 04 FHD² -> Premiere10.br (796)
            ["premiere 04 hd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 04 HD² -> Premiere10.br (796)
            ["premiere 04 sd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 04 SD² -> Premiere10.br (796)
            ["premiere 05"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 05 FHD -> Premiere10.br (796)
            ["premiere 05 fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 05 FHD² -> Premiere10.br (796)
            ["premiere 05 hd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 05 HD² -> Premiere10.br (796)
            ["premiere 06"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 06 FHD -> Premiere10.br (796)
            ["premiere 06 fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 06 FHD² -> Premiere10.br (796)
            ["premiere 06 hd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 06 HD² -> Premiere10.br (796)
            ["premiere 07"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 07 FHD -> Premiere10.br (796)
            ["premiere 08"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE 08 SD -> Premiere10.br (796)
            ["premiere clubes"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE CLUBES FHD -> PremiereClubes.br (798)
            ["premiere clubes fhd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE CLUBES FHD² -> Premiere10.br (796)
            ["premiere clubes hd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE CLUBES HD² -> Premiere10.br (796)
            ["premiere clubes sd2"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Premiere_(2017)_logo.png/960px-Premiere_(2017)_logo.png", // PREMIERE CLUBES SD² -> Premiere10.br (796)
            ["primebox"] = "https://i.imgur.com/BMqSDNn.png", // PRIMEBOX H265 -> PrimeBoxBrazil.br (792)
            ["primebox brazil"] = "https://i.imgur.com/BMqSDNn.png", // PRIMEBOX BRAZIL SD -> PrimeBoxBrazil.br (798)
            ["pt discovery channel"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/2019_Discovery_logo.svg/960px-2019_Discovery_logo.svg.png", // PT: DISCOVERY CHANNEL FHD -> DiscoveryChannel.au (798)
            ["pt nickelodeon"] = "https://i.imgur.com/E84jnP8.png", // PT: NICKELODEON -> Nickelodeon.au (798)
            ["pt nickelodeon junior"] = "https://i.imgur.com/E84jnP8.png", // PT: NICKELODEON JUNIOR -> Nickelodeon.au (798)
            ["record brasilia"] = "https://i.imgur.com/sz9gTTr.png", // RECORD BRASILIA SD -> Record.br (794)
            ["record news"] = "https://i.imgur.com/HZDRG0K.png", // RECORD NEWS FHD -> RecordNews.br (798)
            ["record rs"] = "https://i.imgur.com/JLQWoNc.png", // RECORD RS SD -> RecordRS.br (798)
            ["rede brasil"] = "https://i.imgur.com/TXJKwzZ.png", // REDE BRASIL HD -> RedeBrasil.br (798)
            ["rede gospel"] = "https://i.imgur.com/mttSwgO.png", // REDE GOSPEL FHD -> RedeGospel.br (798)
            ["rede super"] = "https://i.imgur.com/X75qTEm.png", // REDE SUPER -> RedeSuper.br (798)
            ["rede vida"] = "https://i.imgur.com/mP1qfp2.png", // REDE VIDA FHD -> RedeVida.br (798)
            ["star life"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Star_Life_2021.svg/960px-Star_Life_2021.svg.png", // STAR LIFE FHD -> StarLife.bg (798)
            ["studio universal"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/StudioUniversal2016.png/960px-StudioUniversal2016.png", // STUDIO UNIVERSAL FHD -> StudioUniversalAfrica.us (792)
            ["telecine action"] = "https://i.imgur.com/BHYWG0h.png", // TELECINE ACTION 4K -> TelecineAction.br (798)
            ["telecine cult"] = "https://i.imgur.com/6GuHXnr.png", // TELECINE CULT FHD -> TelecineCult.br (798)
            ["telecine fun"] = "https://i.imgur.com/MO2Ynki.png", // TELECINE FUN FHD -> TelecineFun.br (798)
            ["telecine pipoca"] = "https://i.imgur.com/hW9JYXr.png", // TELECINE PIPOCA 4K -> TelecinePipoca.br (798)
            ["telecine premium"] = "https://i.imgur.com/uVFgIr8.png", // TELECINE PREMIUM 4K -> TelecinePremium.br (798)
            ["telecine touch"] = "https://i.imgur.com/Nky0hRo.png", // TELECINE TOUCH FHD -> TelecineTouch.br (798)
            ["terra viva"] = "https://i.imgur.com/wnYsE3O.png", // TERRA VIVA FHD -> TerraViva.br (798)
            ["terraviva"] = "https://i.imgur.com/wnYsE3O.png", // TERRAVIVA SD -> TerraViva.br (798)
            ["tnt series"] = "https://upload.wikimedia.org/wikipedia/commons/7/75/TNT_Series_Logo_2016.png", // TNT SERIES 4K -> TNTSeriesLatinAmerica.us (786)
            ["tnt sports 1"] = "https://github.com/tv-logo/tv-logos/blob/main/countries/united-kingdom/tnt-sports-1-uk.png?raw=true", // TNT SPORTS 1 HD -> TNTSports1.uk (798)
            ["tnt sports 2"] = "https://i.imgur.com/E6pLvOV.png", // TNT SPORTS 2 HD -> TNTSports2.br (798)
            ["tnt sports 3"] = "https://i.imgur.com/LFSMbpN.png", // TNT SPORTS 3 HD -> TNTSports3.br (798)
            ["tnt sports 4"] = "https://i.imgur.com/Am70nWY.png", // TNT SPORTS 4 HD -> TNTSports4.br (798)
            ["tnt sports 5"] = "https://i.imgur.com/XA3zxEE.png", // TNT SPORTS 5 HD -> TNTSports5.br (798)
            ["tooncast"] = "https://i.imgur.com/3yXRbQy.png", // TOONCAST H265 -> Tooncast.us (798)
            ["travel box brazil"] = "https://i.imgur.com/3tBJERH.png", // TRAVEL BOX BRAZIL FHD -> TravelBoxBrazil.br (798)
            ["tv aparecida"] = "https://i.imgur.com/kxrja0X.png", // TV APARECIDA FHD -> TVAparecida.br (798)
            ["tv brasil"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/TvBrasil2023.png/960px-TvBrasil2023.png", // TV BRASIL HD -> TVBrasil.br (798)
            ["tv camara"] = "https://i.imgur.com/Sdou1Ab.png", // TV CAMARA SD -> TVCamara.br (798)
            ["tv cultura"] = "https://i.ibb.co/nm0jXMM/cultura-3x.png", // TV CULTURA FHD -> TVCultura.br (798)
            ["tv evangelizar"] = "https://i.imgur.com/IrYR7Kp.png", // TV EVANGELIZAR -> TVEvangelizar.br (798)
            ["tv justica"] = "https://i.imgur.com/rOQKiMO.png", // TV JUSTIÇA SD -> TVJustica.br (798)
            ["tv ra tim bum"] = "https://i.imgur.com/JIQwz0w.png", // TV RÁ TIM BUM FHD -> TVRaTimBum.br (798)
            ["tv senado"] = "https://i.imgur.com/duy6waL.png", // TV SENADO SD -> TVSenado.br (798)
            ["universal channel"] = "https://i.imgur.com/FI0AtXv.png", // UNIVERSAL CHANNEL FHD -> UniversalChannel.gr (798)
            ["universal tv"] = "https://i.imgur.com/jnjvR5f.png", // UNIVERSAL TV FHD H265 -> UniversalTV.au (798)
            ["urban docs"] = "https://i.imgur.com/hOSHO1T.png", // URBAN DOCS HD -> UrbanDocs.br (798)
            ["urban kids"] = "https://i.imgur.com/bDIeiIH.png", // URBAN KIDS HD -> UrbanKids.br (798)
            ["urban movies"] = "https://i.imgur.com/wcjtSkq.png", // URBAN MOVIES HD -> UrbanMovies.br (798)
            ["urban series"] = "https://i.imgur.com/ZZOiT4x.png", // URBAN SERIES HD -> UrbanSeries.br (798)
            ["usa network"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/USA_Network_logo_%282016%29.svg/960px-USA_Network_logo_%282016%29.svg.png", // USA NETWORK FHD -> USANetwork.us (798)
            ["warner channel"] = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Warner_TV_logo.svg/960px-Warner_TV_logo.svg.png", // WARNER CHANNEL 4K -> WarnerChannel.us (798)
        };

        public static string? TryGetLogoUrl(string? tvgName, string? name, string? tvgId)
        {
            var approvedLogo = MidiaStorageOnlineApprovedChannelMappings.TryGetLogoUrl(tvgName, name, tvgId);
            if (!string.IsNullOrWhiteSpace(approvedLogo))
            {
                return approvedLogo;
            }

            foreach (var candidate in new[] { tvgName, name, tvgId })
            {
                var key = NormalizeChannelName(candidate);
                if (key.Length == 0)
                {
                    continue;
                }

                if (_logos.TryGetValue(key, out var logoUrl))
                {
                    return logoUrl;
                }
            }

            return null;
        }

        private static string NormalizeChannelName(string? text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return string.Empty;
            }

            text = RemoveDiacritics(text).ToLowerInvariant().Trim();
            text = text
                .Replace("¹", "1", StringComparison.Ordinal)
                .Replace("²", "2", StringComparison.Ordinal)
                .Replace("³", "3", StringComparison.Ordinal);
            text = text
                .Replace("fhda2", "fhd2", StringComparison.Ordinal)
                .Replace("hda2", "hd2", StringComparison.Ordinal)
                .Replace("sda2", "sd2", StringComparison.Ordinal);
            text = text.Contains(":", StringComparison.Ordinal)
                ? text[(text.IndexOf(":", StringComparison.Ordinal) + 1)..].Trim()
                : text;
            text = Regex.Replace(text, @"\b(hd|sd|fhd|uhd|4k|8k)\b", " ", RegexOptions.IgnoreCase);
            text = Regex.Replace(text, @"[^a-z0-9]+", " ");
            return Regex.Replace(text, @"\s+", " ").Trim();
        }

        private static string RemoveDiacritics(string text)
        {
            var normalized = text.Normalize(NormalizationForm.FormD);
            var sb = new StringBuilder(normalized.Length);
            foreach (var ch in normalized)
            {
                if (CharUnicodeInfo.GetUnicodeCategory(ch) != UnicodeCategory.NonSpacingMark)
                {
                    sb.Append(ch);
                }
            }

            return sb.ToString().Normalize(NormalizationForm.FormC);
        }
    }
}
