// <auto-generated />
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace MediaBrowser.Providers.Plugins.MidiaStorageOnline
{
    internal sealed record MidiaStorageOnlineApprovedChannelMapping(
        string Name,
        string? EpgId,
        string? MatchedChannel,
        string? LogoUrl);

    internal static class MidiaStorageOnlineApprovedChannelMappings
    {
        private const string ResourceName = "MediaBrowser.Providers.Plugins.MidiaStorageOnline.Data.approved_channels.json";

        private static readonly Lazy<IReadOnlyDictionary<string, MidiaStorageOnlineApprovedChannelMapping>> _exactMappings = new(LoadExactMappings, true);
        private static readonly Lazy<IReadOnlyDictionary<string, MidiaStorageOnlineApprovedChannelMapping>> _relaxedMappings = new(LoadRelaxedMappings, true);

        public static string? TryGetEpgId(string? tvgName, string? name, string? tvgId)
        {
            var mapping = TryGetMapping(tvgName, name, tvgId);
            return string.IsNullOrWhiteSpace(mapping?.EpgId) ? null : mapping.EpgId!.Trim();
        }

        public static string? TryGetLogoUrl(string? tvgName, string? name, string? tvgId)
        {
            var mapping = TryGetMapping(tvgName, name, tvgId);
            return string.IsNullOrWhiteSpace(mapping?.LogoUrl) ? null : mapping.LogoUrl!.Trim();
        }

        public static string? TryGetMatchedChannel(string? tvgName, string? name, string? tvgId)
        {
            var mapping = TryGetMapping(tvgName, name, tvgId);
            return string.IsNullOrWhiteSpace(mapping?.MatchedChannel) ? null : mapping.MatchedChannel!.Trim();
        }

        private static MidiaStorageOnlineApprovedChannelMapping? TryGetMapping(params string?[] candidates)
        {
            var exactMappings = _exactMappings.Value;
            var relaxedMappings = _relaxedMappings.Value;
            foreach (var candidate in candidates)
            {
                var key = NormalizeExactKey(candidate);
                if (key.Length == 0)
                {
                    continue;
                }

                if (exactMappings.TryGetValue(key, out var mapping))
                {
                    return mapping;
                }

                key = NormalizeRelaxedKey(candidate);
                if (key.Length == 0)
                {
                    continue;
                }

                if (relaxedMappings.TryGetValue(key, out mapping))
                {
                    return mapping;
                }
            }

            return null;
        }

        private static IReadOnlyDictionary<string, MidiaStorageOnlineApprovedChannelMapping> LoadExactMappings()
        {
            return LoadMappings(NormalizeExactKey);
        }

        private static IReadOnlyDictionary<string, MidiaStorageOnlineApprovedChannelMapping> LoadRelaxedMappings()
        {
            return LoadMappings(NormalizeRelaxedKey);
        }

        private static IReadOnlyDictionary<string, MidiaStorageOnlineApprovedChannelMapping> LoadMappings(Func<string?, string> normalizeKey)
        {
            var assembly = typeof(MidiaStorageOnlineApprovedChannelMappings).Assembly;
            using var stream = assembly.GetManifestResourceStream(ResourceName)
                ?? throw new InvalidOperationException($"Embedded resource '{ResourceName}' was not found.");
            using var reader = new StreamReader(stream, Encoding.UTF8);
            var json = reader.ReadToEnd();

            var records = JsonSerializer.Deserialize<List<MidiaStorageOnlineApprovedChannelMapping>>(
                json,
                new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                }) ?? [];

            var mappings = new Dictionary<string, MidiaStorageOnlineApprovedChannelMapping>(StringComparer.OrdinalIgnoreCase);
            foreach (var record in records)
            {
                var key = normalizeKey(record.Name);
                if (key.Length == 0 || mappings.ContainsKey(key))
                {
                    continue;
                }

                mappings[key] = record;
            }

            return mappings;
        }

        private static string NormalizeExactKey(string? text)
        {
            return NormalizeKey(text, stripQualityTokens: false);
        }

        private static string NormalizeRelaxedKey(string? text)
        {
            return NormalizeKey(text, stripQualityTokens: true);
        }

        private static string NormalizeKey(string? text, bool stripQualityTokens)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return string.Empty;
            }

            text = RemoveDiacritics(text).ToLowerInvariant().Trim();
            text = text
                .Replace("Â¹", "1", StringComparison.Ordinal)
                .Replace("Â²", "2", StringComparison.Ordinal)
                .Replace("Â³", "3", StringComparison.Ordinal);
            text = text
                .Replace("fhda2", "fhd2", StringComparison.Ordinal)
                .Replace("hda2", "hd2", StringComparison.Ordinal)
                .Replace("sda2", "sd2", StringComparison.Ordinal);
            text = text.Contains(":", StringComparison.Ordinal)
                ? text[(text.IndexOf(":", StringComparison.Ordinal) + 1)..].Trim()
                : text;
            if (stripQualityTokens)
            {
                text = Regex.Replace(text, @"\b(hd|sd|fhd|uhd|4k|8k)\b", " ", RegexOptions.IgnoreCase);
            }
            text = Regex.Replace(text, @"[^a-z0-9]+", " ");
            return Regex.Replace(text, @"\s+", " ").Trim();
        }

        private static string RemoveDiacritics(string text)
        {
            var normalized = text.Normalize(NormalizationForm.FormD);
            var sb = new StringBuilder(normalized.Length);
            foreach (var ch in normalized)
            {
                if (CharUnicodeInfo.GetUnicodeCategory(ch) != UnicodeCategory.NonSpacingMark)
                {
                    sb.Append(ch);
                }
            }

            return sb.ToString().Normalize(NormalizationForm.FormC);
        }
    }
}
