// <auto-generated />
#nullable enable

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using MediaBrowser.Common.Configuration;

namespace MediaBrowser.Providers.Plugins.MidiaStorageOnline
{
    internal static class MidiaStorageOnlineLogoLibrary
    {
        private static readonly HttpClient _httpClient = CreateHttpClient();
        private static readonly SemaphoreSlim _catalogLock = new(1, 1);
        private static readonly ConcurrentDictionary<string, string> _resolvedLogoCache = new(StringComparer.OrdinalIgnoreCase);
        private static IptvOrgLogoCatalog? _catalog;

        private static readonly TimeSpan _catalogTtl = TimeSpan.FromDays(7);
        private const string ChannelsJsonUrl = "https://iptv-org.github.io/api/channels.json";
        private const string LogosJsonUrl = "https://iptv-org.github.io/api/logos.json";

        public static string GetLogoDirectory(IApplicationPaths applicationPaths)
        {
            return Path.Combine(applicationPaths.ProgramDataPath, "midia-online", "logos");
        }

        public static async Task EnsureChannelLogosAsync(IEnumerable<IMidiaStorageOnlineM3uEntry> entries, string baseUrl, IApplicationPaths applicationPaths, CancellationToken ct)
        {
            if (entries is null)
            {
                return;
            }

            var channelEntries = entries
                .Where(e => string.Equals(e.Type, "Canal", StringComparison.OrdinalIgnoreCase))
                .Where(e => !string.IsNullOrWhiteSpace(e.TvgLogo))
                .ToList();

            if (channelEntries.Count == 0)
            {
                return;
            }

            var logoDir = GetLogoDirectory(applicationPaths);
            Directory.CreateDirectory(logoDir);
            baseUrl = baseUrl.TrimEnd('/');

            var catalog = await GetCatalogAsync(applicationPaths, ct).ConfigureAwait(false);

            var uniqueEntries = channelEntries
                .Select(entry => new LogoRequest(entry, entry.TvgLogo!.Trim()))
                .GroupBy(x => x.LogoUrl, StringComparer.OrdinalIgnoreCase)
                .Select(g => g.First())
                .ToList();

            if (uniqueEntries.Count == 0)
            {
                return;
            }

            var results = new ConcurrentDictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var degree = Math.Min(100, Math.Max(4, Environment.ProcessorCount * 2));

            await Parallel.ForEachAsync(uniqueEntries, new ParallelOptions
            {
                MaxDegreeOfParallelism = degree,
                CancellationToken = ct
            },
            async (request, token) =>
            {
                var localUrl = await ResolveLogoAsync(request.Entry, request.LogoUrl, catalog, logoDir, baseUrl, token).ConfigureAwait(false);
                if (!string.IsNullOrWhiteSpace(localUrl))
                {
                    results[request.LogoUrl] = localUrl;
                }
            }).ConfigureAwait(false);

            foreach (var entry in channelEntries)
            {
                var originalLogo = entry.TvgLogo?.Trim();
                if (!string.IsNullOrWhiteSpace(originalLogo)
                    && results.TryGetValue(originalLogo, out var localUrl)
                    && !string.IsNullOrWhiteSpace(localUrl))
                {
                    entry.TvgLogo = localUrl;
                }
            }
        }

        public static string? TryResolveLocalLogoPath(string logoDir, string fileName)
        {
            if (string.IsNullOrWhiteSpace(fileName))
            {
                return null;
            }

            var fullPath = Path.GetFullPath(Path.Combine(logoDir, Path.GetFileName(fileName)));
            var rootFull = Path.GetFullPath(logoDir + Path.DirectorySeparatorChar);
            return fullPath.StartsWith(rootFull, StringComparison.OrdinalIgnoreCase) && File.Exists(fullPath)
                ? fullPath
                : null;
        }

        private static async Task<string?> ResolveLogoAsync(IMidiaStorageOnlineM3uEntry entry, string logoUrl, IptvOrgLogoCatalog catalog, string logoDir, string baseUrl, CancellationToken ct)
        {
            var approvedLogoUrl = MidiaStorageOnlineApprovedChannelMappings.TryGetLogoUrl(entry.TvgName, entry.Name, entry.TvgId);
            if (!string.IsNullOrWhiteSpace(approvedLogoUrl))
            {
                logoUrl = approvedLogoUrl;
            }

            if (TryGetLocalFileName(logoUrl, out var localFileName))
            {
                var existingPath = TryResolveLocalLogoPath(logoDir, localFileName);
                if (!string.IsNullOrWhiteSpace(existingPath))
                {
                    return BuildLocalLogoUrl(baseUrl, localFileName);
                }
            }

            var workbookLogoUrl = MidiaStorageOnlineWorkbookLogoMappings.TryGetLogoUrl(entry.TvgName, entry.Name, entry.TvgId);
            if (!string.IsNullOrWhiteSpace(workbookLogoUrl)
                && !string.Equals(workbookLogoUrl, logoUrl, StringComparison.OrdinalIgnoreCase))
            {
                if (await TryDownloadRemoteLogoAsync(workbookLogoUrl, entry.Name, logoDir, baseUrl, ct).ConfigureAwait(false) is { } workbookDownloaded)
                {
                    return workbookDownloaded;
                }
            }

            if (Uri.TryCreate(logoUrl, UriKind.Absolute, out var uri)
                && (uri.Scheme.Equals(Uri.UriSchemeHttp, StringComparison.OrdinalIgnoreCase)
                    || uri.Scheme.Equals(Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase)))
            {
                if (await TryDownloadRemoteLogoAsync(logoUrl, entry.Name, logoDir, baseUrl, ct).ConfigureAwait(false) is { } downloadedLogo)
                {
                    return downloadedLogo;
                }
            }

            var fallbackLogoUrl = FindIptvOrgLogoUrl(entry.Name, catalog);
            if (!string.IsNullOrWhiteSpace(fallbackLogoUrl)
                && !string.Equals(fallbackLogoUrl, logoUrl, StringComparison.OrdinalIgnoreCase)
                && await TryDownloadRemoteLogoAsync(fallbackLogoUrl, entry.Name, logoDir, baseUrl, ct).ConfigureAwait(false) is { } fallbackDownloaded)
            {
                return fallbackDownloaded;
            }

            return null;
        }

        private static async Task<string?> TryDownloadRemoteLogoAsync(string logoUrl, string channelName, string logoDir, string baseUrl, CancellationToken ct)
        {
            if (string.IsNullOrWhiteSpace(logoUrl) || !Uri.TryCreate(logoUrl, UriKind.Absolute, out var uri))
            {
                return null;
            }

            if (!uri.Scheme.Equals(Uri.UriSchemeHttp, StringComparison.OrdinalIgnoreCase)
                && !uri.Scheme.Equals(Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            var cacheKey = logoUrl.Trim();
            if (_resolvedLogoCache.TryGetValue(cacheKey, out var cachedPath) && File.Exists(cachedPath))
            {
                return BuildLocalLogoUrl(baseUrl, Path.GetFileName(cachedPath));
            }

            var localFileName = BuildLogoFileName(channelName, uri, "jpg");
            var localPath = Path.Combine(logoDir, localFileName);

            if (File.Exists(localPath) && new FileInfo(localPath).Length > 0)
            {
                _resolvedLogoCache[cacheKey] = localPath;
                return BuildLocalLogoUrl(baseUrl, Path.GetFileName(localPath));
            }

            try
            {
                using var response = await _httpClient.GetAsync(uri, HttpCompletionOption.ResponseHeadersRead, ct).ConfigureAwait(false);
                if (!response.IsSuccessStatusCode)
                {
                    return null;
                }

                var contentType = response.Content.Headers.ContentType?.MediaType;
                var extension = GetExtensionFromContentType(contentType, GetExtensionFromUri(uri, "jpg"));
                localFileName = BuildLogoFileName(channelName, uri, extension);
                localPath = Path.Combine(logoDir, localFileName);

                await using var input = await response.Content.ReadAsStreamAsync(ct).ConfigureAwait(false);
                await using var output = new FileStream(localPath, FileMode.Create, FileAccess.Write, FileShare.None, 81920, FileOptions.Asynchronous);
                await input.CopyToAsync(output, ct).ConfigureAwait(false);

                if (new FileInfo(localPath).Length == 0)
                {
                    File.Delete(localPath);
                    return null;
                }

                _resolvedLogoCache[cacheKey] = localPath;
                return BuildLocalLogoUrl(baseUrl, Path.GetFileName(localPath));
            }
            catch
            {
                return null;
            }
        }

        private static string BuildLogoFileName(string channelName, Uri uri, string fallbackExtension)
        {
            var baseName = Uri.UnescapeDataString(Path.GetFileName(uri.AbsolutePath));
            var extension = Path.GetExtension(baseName);
            if (string.IsNullOrWhiteSpace(extension))
            {
                extension = fallbackExtension.StartsWith(".", StringComparison.Ordinal) ? fallbackExtension : "." + fallbackExtension;
            }

            var candidate = string.IsNullOrWhiteSpace(baseName)
                ? $"{SanitizeFileName(channelName)}{extension}"
                : baseName;

            candidate = SanitizeFileName(candidate);
            if (string.IsNullOrWhiteSpace(Path.GetExtension(candidate)))
            {
                candidate += extension;
            }

            return string.IsNullOrWhiteSpace(candidate) ? $"logo{extension}" : candidate;
        }

        private static string SanitizeFileName(string? text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return "logo";
            }

            var invalid = Path.GetInvalidFileNameChars();
            var sb = new StringBuilder(text.Length);
            foreach (var ch in text)
            {
                if (invalid.Contains(ch) || char.IsControl(ch))
                {
                    sb.Append('_');
                }
                else
                {
                    sb.Append(ch);
                }
            }

            var cleaned = Regex.Replace(sb.ToString(), @"\s+", " ").Trim();
            if (cleaned.Length > 120)
            {
                cleaned = cleaned[..120].Trim();
            }

            return string.IsNullOrWhiteSpace(cleaned) ? "logo" : cleaned;
        }

        private static string? FindIptvOrgLogoUrl(string channelName, IptvOrgLogoCatalog catalog)
        {
            var candidates = BuildNameCandidates(channelName).Distinct(StringComparer.OrdinalIgnoreCase);
            var matchedChannelIds = new List<string>();

            foreach (var candidate in candidates)
            {
                if (catalog.ChannelIndex.TryGetValue(candidate, out var exactMatches) && exactMatches.Count > 0)
                {
                    matchedChannelIds.AddRange(exactMatches);
                    break;
                }
            }

            if (matchedChannelIds.Count == 0)
            {
                foreach (var candidate in candidates)
                {
                    foreach (var pair in catalog.ChannelIndex)
                    {
                        if (candidate.Length == 0)
                        {
                            continue;
                        }

                        if (pair.Key.Contains(candidate, StringComparison.OrdinalIgnoreCase)
                            || candidate.Contains(pair.Key, StringComparison.OrdinalIgnoreCase))
                        {
                            matchedChannelIds.AddRange(pair.Value);
                        }
                    }

                    if (matchedChannelIds.Count > 0)
                    {
                        break;
                    }
                }
            }

            if (matchedChannelIds.Count == 0)
            {
                return null;
            }

            var preference = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
            {
                ["PNG"] = 0,
                ["JPEG"] = 1,
                ["JPG"] = 1,
                ["SVG"] = 2,
                ["WEBP"] = 3,
                ["GIF"] = 4,
                ["AVIF"] = 5,
                ["APNG"] = 6
            };

            IptvOrgLogo? bestLogo = null;
            var bestScore = (inUse: int.MaxValue, format: int.MaxValue, width: int.MinValue, height: int.MinValue);

            foreach (var channelId in matchedChannelIds.Distinct(StringComparer.OrdinalIgnoreCase))
            {
                if (!catalog.LogosByChannel.TryGetValue(channelId, out var logos))
                {
                    continue;
                }

                foreach (var logo in logos)
                {
                    var score = (
                        inUse: logo.InUse ? 0 : 1,
                        format: preference.TryGetValue(logo.Format, out var formatScore) ? formatScore : 99,
                        width: -logo.Width,
                        height: -logo.Height);

                    if (bestLogo is null || score.CompareTo(bestScore) < 0)
                    {
                        bestLogo = logo;
                        bestScore = score;
                    }
                }
            }

            return bestLogo?.Url;
        }

        private static IEnumerable<string> BuildNameCandidates(string? channelName)
        {
            var normalized = NormalizeChannelName(channelName);
            if (string.IsNullOrWhiteSpace(normalized))
            {
                yield break;
            }

            yield return normalized;

            var compact = normalized.Replace(" ", string.Empty, StringComparison.Ordinal);
            if (!string.IsNullOrWhiteSpace(compact) && !string.Equals(compact, normalized, StringComparison.OrdinalIgnoreCase))
            {
                yield return compact;
            }

            var strippedPrefix = Regex.Replace(normalized, @"^(canal|channel|tv)\s+", string.Empty, RegexOptions.IgnoreCase).Trim();
            if (!string.IsNullOrWhiteSpace(strippedPrefix) && !string.Equals(strippedPrefix, normalized, StringComparison.OrdinalIgnoreCase))
            {
                yield return strippedPrefix;
            }
        }

        private static string NormalizeChannelName(string? text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return string.Empty;
            }

            text = RemoveDiacritics(text).ToLowerInvariant().Trim();
            text = text.Contains(':', StringComparison.Ordinal)
                ? text[(text.IndexOf(':') + 1)..].Trim()
                : text;
            text = Regex.Replace(text, @"\b(hd|sd|fhd|uhd|4k|8k)\b", " ", RegexOptions.IgnoreCase);
            text = Regex.Replace(text, @"[^a-z0-9]+", " ");
            return Regex.Replace(text, @"\s+", " ").Trim();
        }

        private static string RemoveDiacritics(string text)
        {
            var normalized = text.Normalize(NormalizationForm.FormD);
            var sb = new StringBuilder(normalized.Length);
            foreach (var ch in normalized)
            {
                if (CharUnicodeInfo.GetUnicodeCategory(ch) != UnicodeCategory.NonSpacingMark)
                {
                    sb.Append(ch);
                }
            }

            return sb.ToString().Normalize(NormalizationForm.FormC);
        }

        private static async Task<IptvOrgLogoCatalog> GetCatalogAsync(IApplicationPaths applicationPaths, CancellationToken ct)
        {
            if (_catalog is not null)
            {
                return _catalog;
            }

            await _catalogLock.WaitAsync(ct).ConfigureAwait(false);
            try
            {
                if (_catalog is not null)
                {
                    return _catalog;
                }

                var cacheDir = Path.Combine(applicationPaths.ProgramDataPath, "midia-online", "logo-catalog");
                Directory.CreateDirectory(cacheDir);

                var channelsPath = Path.Combine(cacheDir, "channels.json");
                var logosPath = Path.Combine(cacheDir, "logos.json");

                await EnsureCachedFileAsync(ChannelsJsonUrl, channelsPath, ct).ConfigureAwait(false);
                await EnsureCachedFileAsync(LogosJsonUrl, logosPath, ct).ConfigureAwait(false);

                var channelsJson = await File.ReadAllTextAsync(channelsPath, ct).ConfigureAwait(false);
                var logosJson = await File.ReadAllTextAsync(logosPath, ct).ConfigureAwait(false);

                using var channelsDoc = JsonDocument.Parse(channelsJson);
                using var logosDoc = JsonDocument.Parse(logosJson);
                _catalog = BuildCatalog(channelsDoc, logosDoc);
                return _catalog;
            }
            finally
            {
                _catalogLock.Release();
            }
        }

        private static IptvOrgLogoCatalog BuildCatalog(JsonDocument channelsDoc, JsonDocument logosDoc)
        {
            var channelIndex = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
            foreach (var channel in channelsDoc.RootElement.EnumerateArray())
            {
                var id = GetJsonString(channel, "id");
                if (string.IsNullOrWhiteSpace(id))
                {
                    continue;
                }

                var names = new List<string>();
                var name = GetJsonString(channel, "name");
                if (!string.IsNullOrWhiteSpace(name))
                {
                    names.Add(name!);
                }

                if (channel.TryGetProperty("alt_names", out var altNames) && altNames.ValueKind == JsonValueKind.Array)
                {
                    foreach (var altName in altNames.EnumerateArray())
                    {
                        var value = altName.GetString();
                        if (!string.IsNullOrWhiteSpace(value))
                        {
                            names.Add(value);
                        }
                    }
                }

                foreach (var candidate in names)
                {
                    var key = NormalizeChannelName(candidate);
                    if (string.IsNullOrWhiteSpace(key))
                    {
                        continue;
                    }

                    if (!channelIndex.TryGetValue(key, out var bucket))
                    {
                        bucket = new List<string>();
                        channelIndex[key] = bucket;
                    }

                    bucket.Add(id);
                }
            }

            var logosByChannel = new Dictionary<string, List<IptvOrgLogo>>(StringComparer.OrdinalIgnoreCase);
            foreach (var logo in logosDoc.RootElement.EnumerateArray())
            {
                var channelId = GetJsonString(logo, "channel");
                var url = GetJsonString(logo, "url");
                if (string.IsNullOrWhiteSpace(channelId) || string.IsNullOrWhiteSpace(url))
                {
                    continue;
                }

                var inUse = GetJsonBoolean(logo, "in_use");
                var format = GetJsonString(logo, "format")?.ToUpperInvariant() ?? string.Empty;
                var width = GetJsonInt32(logo, "width");
                var height = GetJsonInt32(logo, "height");

                if (!logosByChannel.TryGetValue(channelId, out var bucket))
                {
                    bucket = new List<IptvOrgLogo>();
                    logosByChannel[channelId] = bucket;
                }

                bucket.Add(new IptvOrgLogo(channelId, url!, inUse, format, width, height));
            }

            return new IptvOrgLogoCatalog(channelIndex, logosByChannel);
        }

        private static string? GetJsonString(JsonElement element, string propertyName)
        {
            return element.TryGetProperty(propertyName, out var property) ? property.GetString() : null;
        }

        private static bool GetJsonBoolean(JsonElement element, string propertyName)
        {
            return element.TryGetProperty(propertyName, out var property) && property.ValueKind == JsonValueKind.True;
        }

        private static int GetJsonInt32(JsonElement element, string propertyName)
        {
            return element.TryGetProperty(propertyName, out var property) && property.TryGetInt32(out var value)
                ? value
                : 0;
        }

        private static async Task EnsureCachedFileAsync(string sourceUrl, string path, CancellationToken ct)
        {
            var needsRefresh = !File.Exists(path);
            if (!needsRefresh)
            {
                var fileInfo = new FileInfo(path);
                needsRefresh = fileInfo.Length == 0 || DateTime.UtcNow - fileInfo.LastWriteTimeUtc > _catalogTtl;
            }

            if (!needsRefresh)
            {
                return;
            }

            using var response = await _httpClient.GetAsync(sourceUrl, ct).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();

            await using var source = await response.Content.ReadAsStreamAsync(ct).ConfigureAwait(false);
            await using var fileStream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None, 81920, FileOptions.Asynchronous);
            await source.CopyToAsync(fileStream, ct).ConfigureAwait(false);
        }

        private static string BuildLocalLogoUrl(string baseUrl, string fileName)
        {
            return $"{baseUrl}/MidiaStorageOnline/logos/{Uri.EscapeDataString(Path.GetFileName(fileName))}";
        }

        private static bool TryGetLocalFileName(string url, out string fileName)
        {
            fileName = string.Empty;
            if (!Uri.TryCreate(url, UriKind.Absolute, out var uri))
            {
                return false;
            }

            if (!uri.AbsolutePath.Contains("/MidiaStorageOnline/logos/", StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            fileName = Path.GetFileName(uri.LocalPath);
            return !string.IsNullOrWhiteSpace(fileName);
        }

        private static string GetExtensionFromUri(Uri uri, string fallback)
        {
            var ext = Path.GetExtension(uri.AbsolutePath);
            if (!string.IsNullOrWhiteSpace(ext))
            {
                return ext.TrimStart('.');
            }

            return fallback;
        }

        private static string GetExtensionFromContentType(string? contentType, string fallback)
        {
            if (string.IsNullOrWhiteSpace(contentType))
            {
                return fallback;
            }

            return contentType.ToLowerInvariant() switch
            {
                "image/jpeg" => "jpg",
                "image/jpg" => "jpg",
                "image/png" => "png",
                "image/webp" => "webp",
                "image/gif" => "gif",
                "image/svg+xml" => "svg",
                _ => fallback
            };
        }

        private static HttpClient CreateHttpClient()
        {
            var client = new HttpClient(new HttpClientHandler
            {
                AutomaticDecompression = DecompressionMethods.All,
                CheckCertificateRevocationList = true
            });

            client.Timeout = TimeSpan.FromSeconds(30);
            client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
            return client;
        }

        private sealed record LogoRequest(IMidiaStorageOnlineM3uEntry Entry, string LogoUrl);

        private sealed record IptvOrgLogo(string ChannelId, string Url, bool InUse, string Format, int Width, int Height);

        private sealed record IptvOrgLogoCatalog(
            Dictionary<string, List<string>> ChannelIndex,
            Dictionary<string, List<IptvOrgLogo>> LogosByChannel);
    }
}
