// <auto-generated />
#nullable enable
using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace MediaBrowser.Providers.Plugins.MidiaStorageOnline.ScheduledTasks
{
    /// <summary>
    /// Aggregate metrics for the online media synchronization task.
    /// </summary>
    public static class MidiaStorageOnlineSyncMetrics
    {
        public const string MeterName = "MulletaFlix.Providers.MidiaStorageOnlineSync";

        private static readonly Meter SyncMeter = new(MeterName);
        private static readonly Counter<long> Runs = SyncMeter.CreateCounter<long>("mulletaflix.media_sync.runs");
        private static readonly Counter<long> ParsedEntries = SyncMeter.CreateCounter<long>("mulletaflix.media_sync.entries.parsed");
        private static readonly Counter<long> ParsedChannels = SyncMeter.CreateCounter<long>("mulletaflix.media_sync.channels.parsed");
        private static readonly Counter<long> ParsedMedia = SyncMeter.CreateCounter<long>("mulletaflix.media_sync.media.parsed");
        private static readonly Histogram<double> Duration = SyncMeter.CreateHistogram<double>("mulletaflix.media_sync.duration", "s");
        private static readonly UpDownCounter<long> ActiveRuns = SyncMeter.CreateUpDownCounter<long>("mulletaflix.media_sync.active_runs");

        public static void RecordActive(long delta) => ActiveRuns.Add(delta);

        public static void RecordRun(string result, double durationSeconds)
        {
            var tags = new TagList { { "result", result } };
            Runs.Add(1, tags);
            Duration.Record(durationSeconds, tags);
        }

        public static void RecordParsedEntries(long entries, long channels, long media)
        {
            ParsedEntries.Add(entries);
            ParsedChannels.Add(channels);
            ParsedMedia.Add(media);
        }
    }
}
