package org.mulletaflix.feature.auth

import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusDirection
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.testTagsAsResourceId
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import android.widget.Toast
import coil.compose.AsyncImagePainter
import coil.compose.SubcomposeAsyncImage
import coil.compose.SubcomposeAsyncImageContent
import org.mulletaflix.designsystem.media.LocalMulletaFlixAccessToken
import org.mulletaflix.designsystem.media.LocalMulletaFlixServerUrl
import org.mulletaflix.designsystem.media.resolveMediaUrl
import org.mulletaflix.designsystem.components.MulletaFlixWordmark
import org.mulletaflix.designsystem.components.MulletaFlixTopBarAction
import org.mulletaflix.designsystem.components.remoteFocusRing
import org.mulletaflix.designsystem.theme.MulletaFlixRed

internal const val REGISTER_DIALOG_CONTENT_DESCRIPTION = "Conteúdo do cadastro; deslize verticalmente para ver mais"
internal const val LOGIN_USERNAME_TEST_TAG = "auth.login.username"
internal const val LOGIN_PASSWORD_TEST_TAG = "auth.login.password"
internal const val LOGIN_SUBMIT_TEST_TAG = "auth.login.submit"
internal const val QUICK_CONNECT_TAB_TEST_TAG = "auth.quick_connect.tab"
internal const val QUICK_CONNECT_INITIATE_TEST_TAG = "auth.quick_connect.initiate"
internal const val QUICK_CONNECT_RETRY_AVAILABILITY_TEST_TAG = "auth.quick_connect.retry_availability"
internal const val QUICK_CONNECT_CODE_TEST_TAG = "auth.quick_connect.code"

/**
 * Login screen — first authentication step after server is selected.
 *
 * Supports:
 *  1. Username + Password (classic)
 *  2. Quick Connect (6-digit PIN generated by server)
 *  3. Password-less login (if server allows it)
 *
 * Design: Dark background (#101010), MulletaFlix logo, red accent
 */
@Composable
fun LoginScreen(
    onLoginSuccess: () -> Unit,
    switchingServer: Boolean = false,
    viewModel: AuthViewModel = hiltViewModel()
) {
    val state by viewModel.state.collectAsStateWithLifecycle()
    val focusManager = LocalFocusManager.current
    val context = LocalContext.current
    var showRegisterDialog by remember { mutableStateOf(false) }

    // Quick Connect is scoped to this authentication surface. Leaving the
    // screen must not leave a background poll that can authenticate a later
    // session or keep the network active after navigation.
    DisposableEffect(viewModel) {
        onDispose { viewModel.cancelQuickConnect() }
    }

    LaunchedEffect(state.isAuthenticated, switchingServer) {
        if (shouldAutoAdvanceAuthScreen(state.isAuthenticated, switchingServer)) onLoginSuccess()
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.verticalGradient(
                    colors = listOf(AuthBackdropTop, AuthBackdropBottom)
                )
            )
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(24.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {

            // ── Logo ──────────────────────────────────────────────────────────
            Icon(
                painter = painterResource(id = org.mulletaflix.designsystem.R.drawable.ic_mulletaflix_logo),
                contentDescription = "MulletaFlix",
                tint = Color.Unspecified,
                modifier = Modifier.size(80.dp)
            )

            MulletaFlixWordmark(
                style = MaterialTheme.typography.headlineMedium,
                fontWeight = FontWeight.Bold,
                modifier = Modifier.padding(top = 12.dp)
            )

            Text(
                text = state.serverUrl ?: "",
                style = MaterialTheme.typography.bodySmall,
                color = Color.White.copy(alpha = 0.5f),
                modifier = Modifier.padding(top = 4.dp, bottom = 32.dp)
            )

            // ── Tab Selector (Login / Quick Connect) ──────────────────────────
            var selectedTab by remember { mutableIntStateOf(0) }
            LaunchedEffect(selectedTab) {
                if (selectedTab == 0) viewModel.cancelQuickConnect()
            }
            PrimaryTabRow(
                selectedTabIndex = selectedTab,
                containerColor = MaterialTheme.colorScheme.surface,
                contentColor = MaterialTheme.colorScheme.secondary,
                indicator = {
                    TabRowDefaults.PrimaryIndicator(color = MulletaFlixRed)
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(RoundedCornerShape(12.dp))
            ) {
                Tab(
                    selected = selectedTab == 0,
                    onClick = { selectedTab = 0 },
                    modifier = Modifier.remoteFocusRing(RoundedCornerShape(12.dp)),
                ) {
                    Text("Entrar", modifier = Modifier.padding(vertical = 12.dp))
                }
                Tab(
                    selected = selectedTab == 1,
                    onClick = { selectedTab = 1 },
                    modifier = Modifier
                        .remoteFocusRing(RoundedCornerShape(12.dp))
                        .testTag(QUICK_CONNECT_TAB_TEST_TAG),
                ) {
                    Text("Quick Connect", modifier = Modifier.padding(vertical = 12.dp))
                }
            }

            Spacer(modifier = Modifier.height(24.dp))

            AnimatedContent(targetState = selectedTab) { tab ->
                when (tab) {
                    0 -> PasswordLoginForm(
                        username = state.username,
                        password = state.password,
                        isLoading = state.isLoading,
                        error = state.error,
                        onUsernameChange = viewModel::onUsernameChange,
                        onPasswordChange = viewModel::onPasswordChange,
                        onLogin = { viewModel.login() },
                        users = state.availableUsers,
                        onUserSelect = viewModel::onUserSelect,
                        onRegister = { showRegisterDialog = true },
                    )
                    1 -> QuickConnectForm(
                        pin = state.quickConnectPin,
                        isLoading = state.isLoading,
                        isWaiting = state.isWaitingForQuickConnect,
                        isAvailable = state.isQuickConnectAvailable,
                        availabilityError = state.quickConnectAvailabilityError,
                        secondsRemaining = state.quickConnectSecondsRemaining,
                        error = state.error,
                        onInitiate = { viewModel.initiateQuickConnect() },
                        onRetryAvailability = { viewModel.retryQuickConnectAvailability() },
                        onCancel = { viewModel.cancelQuickConnect() },
                        onCopyPin = { pin ->
                            val clipboard = context.getSystemService(android.content.ClipboardManager::class.java)
                            clipboard?.setPrimaryClip(android.content.ClipData.newPlainText("Código Quick Connect", pin))
                            Toast.makeText(context, "Código copiado", Toast.LENGTH_SHORT).show()
                        },
                    )
                }
            }
        }
    }

    if (showRegisterDialog) {
        RegisterDialog(
            isLoading = state.isRegistering,
            error = state.error,
            onDismiss = { if (!state.isRegistering) showRegisterDialog = false },
            onRegister = { username, password, confirmation ->
                if (password != confirmation) {
                    Toast.makeText(context, "As senhas não conferem", Toast.LENGTH_SHORT).show()
                } else {
                    viewModel.register(username, password) {
                        showRegisterDialog = false
                        viewModel.login(username, password)
                        Toast.makeText(context, "Cadastro realizado com sucesso. Sua conta recebeu 30 minutos de teste.", Toast.LENGTH_LONG).show()
                    }
                }
            },
        )
    }
}

@Composable
internal fun PasswordLoginForm(
    username: String,
    password: String,
    isLoading: Boolean,
    error: String?,
    onUsernameChange: (String) -> Unit,
    onPasswordChange: (String) -> Unit,
    onLogin: () -> Unit,
    users: List<AuthUser>,
    onUserSelect: (AuthUser) -> Unit,
    onRegister: () -> Unit,
) {
    val focusManager = LocalFocusManager.current
    var passwordVisible by remember { mutableStateOf(false) }

    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp),
        modifier = Modifier.semantics { testTagsAsResourceId = true },
    ) {
        // User avatars (if server has multiple users)
        if (users.isNotEmpty()) {
            UserAvatarRow(users = users, onUserSelect = onUserSelect)
        }

        // Username field
        OutlinedTextField(
            value = username,
            onValueChange = onUsernameChange,
            label = { Text("Usuário") },
            leadingIcon = { Icon(Icons.Default.Person, contentDescription = null) },
            singleLine = true,
            keyboardOptions = KeyboardOptions(imeAction = ImeAction.Next),
            keyboardActions = KeyboardActions(onNext = { focusManager.moveFocus(FocusDirection.Down) }),
            modifier = Modifier.fillMaxWidth().testTag(LOGIN_USERNAME_TEST_TAG),
            enabled = !isLoading,
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = MaterialTheme.colorScheme.secondary,
                cursorColor = MaterialTheme.colorScheme.secondary,
            )
        )

        // Password field
        OutlinedTextField(
            value = password,
            onValueChange = onPasswordChange,
            label = { Text("Senha") },
            leadingIcon = { Icon(Icons.Default.Lock, contentDescription = null) },
            trailingIcon = {
                MulletaFlixTopBarAction(onClick = { passwordVisible = !passwordVisible }) {
                    Icon(
                        if (passwordVisible) Icons.Outlined.Visibility else Icons.Outlined.VisibilityOff,
                        contentDescription = if (passwordVisible) "Ocultar senha" else "Mostrar senha"
                    )
                }
            },
            visualTransformation = if (passwordVisible) VisualTransformation.None else PasswordVisualTransformation(),
            singleLine = true,
            keyboardOptions = KeyboardOptions(
                keyboardType = KeyboardType.Password,
                imeAction = ImeAction.Done
            ),
            keyboardActions = KeyboardActions(onDone = { onLogin() }),
            modifier = Modifier.fillMaxWidth().testTag(LOGIN_PASSWORD_TEST_TAG),
            enabled = !isLoading,
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = MaterialTheme.colorScheme.secondary,
                cursorColor = MaterialTheme.colorScheme.secondary,
            )
        )

        // Error message
        error?.let {
            Text(text = it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
        }

        // Login button
        Button(
            onClick = onLogin,
            enabled = !isLoading && username.isNotBlank(),
            modifier = Modifier
                .fillMaxWidth()
                .height(52.dp)
                .remoteFocusRing(RoundedCornerShape(12.dp))
                .testTag(LOGIN_SUBMIT_TEST_TAG),
            shape = RoundedCornerShape(12.dp),
            colors = ButtonDefaults.buttonColors(containerColor = MulletaFlixRed),
        ) {
            if (isLoading) {
                CircularProgressIndicator(modifier = Modifier.size(20.dp), color = Color.White, strokeWidth = 2.dp)
            } else {
                Text("Entrar", style = MaterialTheme.typography.labelLarge)
            }
        }

        OutlinedButton(
            onClick = onRegister,
            enabled = !isLoading,
            modifier = Modifier
                .fillMaxWidth()
                .height(52.dp)
                .remoteFocusRing(RoundedCornerShape(12.dp)),
            shape = RoundedCornerShape(12.dp),
            colors = ButtonDefaults.outlinedButtonColors(contentColor = MaterialTheme.colorScheme.secondary),
        ) {
            Text("Cadastrar", style = MaterialTheme.typography.labelLarge)
        }
    }
}

@Composable
internal fun RegisterDialog(
    isLoading: Boolean,
    error: String?,
    onDismiss: () -> Unit,
    onRegister: (String, String, String) -> Unit,
) {
    var username by remember { mutableStateOf("") }
    var password by remember { mutableStateOf("") }
    var confirmation by remember { mutableStateOf("") }
    var passwordVisible by remember { mutableStateOf(false) }
    var confirmationVisible by remember { mutableStateOf(false) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Criar Conta") },
        text = {
            Column(
                modifier = Modifier
                    .heightIn(max = 360.dp)
                    .verticalScroll(rememberScrollState())
                    .semantics {
                        contentDescription = REGISTER_DIALOG_CONTENT_DESCRIPTION
                    },
                verticalArrangement = Arrangement.spacedBy(12.dp),
            ) {
                Text("Crie sua conta para acessar o Mulletaflix.", style = MaterialTheme.typography.bodySmall)
                OutlinedTextField(
                    value = username,
                    onValueChange = { username = it },
                    label = { Text("E-mail ou usuário") },
                    singleLine = true,
                    enabled = !isLoading,
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Email),
                    modifier = Modifier.fillMaxWidth(),
                )
                OutlinedTextField(
                    value = password,
                    onValueChange = { password = it },
                    label = { Text("Senha") },
                    singleLine = true,
                    enabled = !isLoading,
                    trailingIcon = {
                        MulletaFlixTopBarAction(onClick = { passwordVisible = !passwordVisible }) {
                            Icon(
                                if (passwordVisible) Icons.Outlined.Visibility else Icons.Outlined.VisibilityOff,
                                contentDescription = if (passwordVisible) "Ocultar senha" else "Mostrar senha",
                            )
                        }
                    },
                    visualTransformation = if (passwordVisible) VisualTransformation.None else PasswordVisualTransformation(),
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                    modifier = Modifier.fillMaxWidth(),
                )
                OutlinedTextField(
                    value = confirmation,
                    onValueChange = { confirmation = it },
                    label = { Text("Confirmar senha") },
                    singleLine = true,
                    enabled = !isLoading,
                    trailingIcon = {
                        MulletaFlixTopBarAction(onClick = { confirmationVisible = !confirmationVisible }) {
                            Icon(
                                if (confirmationVisible) Icons.Outlined.Visibility else Icons.Outlined.VisibilityOff,
                                contentDescription = if (confirmationVisible) "Ocultar confirmação" else "Mostrar confirmação",
                            )
                        }
                    },
                    visualTransformation = if (confirmationVisible) VisualTransformation.None else PasswordVisualTransformation(),
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                    modifier = Modifier.fillMaxWidth(),
                )
                error?.let { Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall) }
            }
        },
        confirmButton = {
            Button(
                onClick = { onRegister(username, password, confirmation) },
                enabled = !isLoading,
                modifier = Modifier.remoteFocusRing(RoundedCornerShape(12.dp)),
            ) {
                if (isLoading) CircularProgressIndicator(modifier = Modifier.size(20.dp), strokeWidth = 2.dp)
                else Text("Cadastrar")
            }
        },
        dismissButton = {
            TextButton(
                onClick = onDismiss,
                enabled = !isLoading,
                modifier = Modifier.remoteFocusRing(RoundedCornerShape(12.dp)),
            ) { Text("Voltar") }
        },
    )
}

@Composable
internal fun QuickConnectForm(
    pin: String?,
    isAvailable: Boolean?,
    availabilityError: String?,
    isLoading: Boolean,
    isWaiting: Boolean,
    secondsRemaining: Int?,
    error: String?,
    onInitiate: () -> Unit,
    onRetryAvailability: () -> Unit,
    onCancel: () -> Unit,
    onCopyPin: (String) -> Unit,
) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        if (pin != null) {
            Text("Digite este código no servidor:", style = MaterialTheme.typography.bodyMedium, color = Color.White)
            Text(
                text = pin,
                style = MaterialTheme.typography.displaySmall,
                color = MaterialTheme.colorScheme.secondary,
                fontWeight = FontWeight.Bold,
                letterSpacing = 8.sp,
                modifier = Modifier.testTag(QUICK_CONNECT_CODE_TEST_TAG),
            )
            OutlinedButton(
                onClick = { onCopyPin(pin) },
                modifier = Modifier.remoteFocusRing(RoundedCornerShape(12.dp)),
            ) {
                Icon(Icons.Default.ContentCopy, contentDescription = null)
                Spacer(Modifier.width(8.dp))
                Text("Copiar código")
            }
            if (isWaiting) {
                CircularProgressIndicator(color = MaterialTheme.colorScheme.secondary)
                Text("Aguardando autorização...", color = Color.White.copy(0.7f))
                secondsRemaining?.let { remaining ->
                    Text(
                        text = "Expira em ${remaining / 60}:${(remaining % 60).toString().padStart(2, '0')}",
                        color = Color.White.copy(0.7f),
                        style = MaterialTheme.typography.labelMedium,
                    )
                }
            }
            OutlinedButton(
                onClick = onCancel,
                modifier = Modifier.remoteFocusRing(RoundedCornerShape(12.dp)),
            ) { Text("Cancelar") }
        } else if (isAvailable == null && availabilityError == null) {
            CircularProgressIndicator(color = MaterialTheme.colorScheme.secondary, modifier = Modifier.size(32.dp))
            Text("Verificando Quick Connect…", color = Color.White.copy(0.8f), style = MaterialTheme.typography.bodyMedium)
        } else if (isAvailable == null) {
            Text(
                availabilityError ?: "Não foi possível verificar o Quick Connect.",
                color = MaterialTheme.colorScheme.error,
                style = MaterialTheme.typography.bodyMedium,
            )
            OutlinedButton(
                onClick = onRetryAvailability,
                modifier = Modifier
                    .remoteFocusRing(RoundedCornerShape(12.dp))
                    .testTag(QUICK_CONNECT_RETRY_AVAILABILITY_TEST_TAG),
            ) { Text("Tentar novamente") }
        } else if (!isAvailable) {
            Icon(Icons.Default.QrCode2, contentDescription = "Quick Connect", tint = MaterialTheme.colorScheme.secondary, modifier = Modifier.size(64.dp))
            Text("Quick Connect está desativado neste servidor.", color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodyMedium)
            Text("Use a aba Entrar para acessar com usuário e senha.", color = Color.White.copy(0.8f), style = MaterialTheme.typography.bodySmall)
        } else {
            Text("Gera um código de 6 dígitos para entrar sem senha.", style = MaterialTheme.typography.bodyMedium, color = Color.White.copy(0.8f))
            error?.let { Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall) }
            Button(
                onClick = onInitiate,
                enabled = !isLoading,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(52.dp)
                    .remoteFocusRing(RoundedCornerShape(12.dp))
                    .testTag(QUICK_CONNECT_INITIATE_TEST_TAG),
                shape = RoundedCornerShape(12.dp),
            ) {
                if (isLoading) CircularProgressIndicator(modifier = Modifier.size(20.dp), color = Color.White, strokeWidth = 2.dp)
                else Text("Gerar Código Quick Connect")
            }
        }
    }
}

@Composable
private fun UserAvatarRow(
    users: List<AuthUser>,
    onUserSelect: (AuthUser) -> Unit,
) {
    val serverUrl = LocalMulletaFlixServerUrl.current
    val accessToken = LocalMulletaFlixAccessToken.current
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        Text("Escolha um usuário", color = Color.White.copy(alpha = 0.7f), style = MaterialTheme.typography.labelMedium)
        Spacer(Modifier.height(8.dp))
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(16.dp, Alignment.CenterHorizontally),
        ) {
            users.take(6).forEach { user ->
                    Column(
                        horizontalAlignment = Alignment.CenterHorizontally,
                        modifier = Modifier
                            .width(72.dp)
                            .clickable { onUserSelect(user) }
                            .semantics(mergeDescendants = true) {
                                contentDescription = "Selecionar ${user.name}"
                            }
                            .remoteFocusRing(RoundedCornerShape(18.dp)),
                    ) {
                    val imagePath = user.primaryImageTag?.let { tag ->
                        "Users/${user.id}/Images/Primary?tag=$tag"
                    }
                    SubcomposeAsyncImage(
                        model = resolveMediaUrl(serverUrl, imagePath, accessToken),
                        contentDescription = "Selecionar ${user.name}",
                        modifier = Modifier
                            .size(56.dp)
                            .clip(RoundedCornerShape(18.dp))
                            .background(MaterialTheme.colorScheme.surfaceVariant),
                        contentScale = androidx.compose.ui.layout.ContentScale.Crop,
                    ) {
                        when (painter.state) {
                            is AsyncImagePainter.State.Success -> SubcomposeAsyncImageContent()
                            else -> Box(
                                modifier = Modifier.fillMaxSize(),
                                contentAlignment = Alignment.Center,
                            ) {
                                Text(
                                    text = userInitial(user.name),
                                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                                    style = MaterialTheme.typography.titleMedium,
                                    fontWeight = FontWeight.Bold,
                                )
                            }
                        }
                    }
                    Text(
                        user.name,
                        color = Color.White,
                        style = MaterialTheme.typography.labelSmall,
                        maxLines = 1,
                        overflow = androidx.compose.ui.text.style.TextOverflow.Ellipsis,
                        modifier = Modifier.padding(top = 4.dp),
                    )
                }
            }
        }
    }
}

internal fun userInitial(name: String): String =
    name.trim().firstOrNull()?.uppercaseChar()?.toString() ?: "?"

private val Int.sp get() = androidx.compose.ui.unit.TextUnit(this.toFloat(), androidx.compose.ui.unit.TextUnitType.Sp)
