package org.mulletaflix.feature.auth

import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusDirection
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel

/**
 * Login screen — first authentication step after server is selected.
 *
 * Supports:
 *  1. Username + Password (classic)
 *  2. Quick Connect (6-digit PIN generated by server)
 *  3. Password-less login (if server allows it)
 *
 * Design: Dark background (#101010), MulletaFlix logo, blue accent
 */
@Composable
fun LoginScreen(
    onLoginSuccess: () -> Unit,
    viewModel: AuthViewModel = hiltViewModel()
) {
    val state by viewModel.state.collectAsState()
    val focusManager = LocalFocusManager.current

    LaunchedEffect(state.isAuthenticated) {
        if (state.isAuthenticated) onLoginSuccess()
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.verticalGradient(
                    colors = listOf(Color(0xFF0A1628), Color(0xFF101010))
                )
            )
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(24.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {

            // ── Logo ──────────────────────────────────────────────────────────
            Icon(
                painter = painterResource(id = org.mulletaflix.designsystem.R.drawable.ic_mulletaflix_logo),
                contentDescription = "MulletaFlix",
                tint = Color(0xFF00A4DC),
                modifier = Modifier.size(80.dp)
            )

            Text(
                text = "MulletaFlix",
                style = MaterialTheme.typography.headlineMedium,
                color = Color.White,
                fontWeight = FontWeight.Bold,
                modifier = Modifier.padding(top = 12.dp)
            )

            Text(
                text = state.serverUrl ?: "",
                style = MaterialTheme.typography.bodySmall,
                color = Color.White.copy(alpha = 0.5f),
                modifier = Modifier.padding(top = 4.dp, bottom = 32.dp)
            )

            // ── Tab Selector (Login / Quick Connect) ──────────────────────────
            var selectedTab by remember { mutableIntStateOf(0) }
            TabRow(
                selectedTabIndex = selectedTab,
                containerColor = Color(0xFF1A1A1A),
                contentColor = Color(0xFF00A4DC),
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(RoundedCornerShape(12.dp))
            ) {
                Tab(selected = selectedTab == 0, onClick = { selectedTab = 0 }) {
                    Text("Entrar", modifier = Modifier.padding(vertical = 12.dp))
                }
                Tab(selected = selectedTab == 1, onClick = { selectedTab = 1 }) {
                    Text("Quick Connect", modifier = Modifier.padding(vertical = 12.dp))
                }
            }

            Spacer(modifier = Modifier.height(24.dp))

            AnimatedContent(targetState = selectedTab) { tab ->
                when (tab) {
                    0 -> PasswordLoginForm(
                        username = state.username,
                        password = state.password,
                        isLoading = state.isLoading,
                        error = state.error,
                        onUsernameChange = viewModel::onUsernameChange,
                        onPasswordChange = viewModel::onPasswordChange,
                        onLogin = { viewModel.login() },
                        users = state.availableUsers,
                        onUserSelect = viewModel::onUserSelect,
                    )
                    1 -> QuickConnectForm(
                        pin = state.quickConnectPin,
                        isLoading = state.isLoading,
                        isWaiting = state.isWaitingForQuickConnect,
                        error = state.error,
                        onInitiate = { viewModel.initiateQuickConnect() },
                        onCancel = { viewModel.cancelQuickConnect() },
                    )
                }
            }
        }
    }
}

@Composable
private fun PasswordLoginForm(
    username: String,
    password: String,
    isLoading: Boolean,
    error: String?,
    onUsernameChange: (String) -> Unit,
    onPasswordChange: (String) -> Unit,
    onLogin: () -> Unit,
    users: List<org.mulletaflix.domain.model.UserInfo>,
    onUserSelect: (org.mulletaflix.domain.model.UserInfo) -> Unit,
) {
    val focusManager = LocalFocusManager.current
    var passwordVisible by remember { mutableStateOf(false) }

    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        // User avatars (if server has multiple users)
        if (users.isNotEmpty()) {
            UserAvatarRow(users = users, onUserSelect = onUserSelect)
        }

        // Username field
        OutlinedTextField(
            value = username,
            onValueChange = onUsernameChange,
            label = { Text("Usuário") },
            leadingIcon = { Icon(Icons.Default.Person, contentDescription = null) },
            singleLine = true,
            keyboardOptions = KeyboardOptions(imeAction = ImeAction.Next),
            keyboardActions = KeyboardActions(onNext = { focusManager.moveFocus(FocusDirection.Down) }),
            modifier = Modifier.fillMaxWidth(),
            enabled = !isLoading,
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = Color(0xFF00A4DC),
                cursorColor = Color(0xFF00A4DC),
            )
        )

        // Password field
        OutlinedTextField(
            value = password,
            onValueChange = onPasswordChange,
            label = { Text("Senha") },
            leadingIcon = { Icon(Icons.Default.Lock, contentDescription = null) },
            trailingIcon = {
                IconButton(onClick = { passwordVisible = !passwordVisible }) {
                    Icon(
                        if (passwordVisible) Icons.Outlined.Visibility else Icons.Outlined.VisibilityOff,
                        contentDescription = if (passwordVisible) "Ocultar senha" else "Mostrar senha"
                    )
                }
            },
            visualTransformation = if (passwordVisible) VisualTransformation.None else PasswordVisualTransformation(),
            singleLine = true,
            keyboardOptions = KeyboardOptions(
                keyboardType = KeyboardType.Password,
                imeAction = ImeAction.Done
            ),
            keyboardActions = KeyboardActions(onDone = { onLogin() }),
            modifier = Modifier.fillMaxWidth(),
            enabled = !isLoading,
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = Color(0xFF00A4DC),
                cursorColor = Color(0xFF00A4DC),
            )
        )

        // Error message
        error?.let {
            Text(text = it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
        }

        // Login button
        Button(
            onClick = onLogin,
            enabled = !isLoading && username.isNotBlank(),
            modifier = Modifier
                .fillMaxWidth()
                .height(52.dp),
            shape = RoundedCornerShape(12.dp)
        ) {
            if (isLoading) {
                CircularProgressIndicator(modifier = Modifier.size(20.dp), color = Color.White, strokeWidth = 2.dp)
            } else {
                Text("Entrar", style = MaterialTheme.typography.labelLarge)
            }
        }
    }
}

@Composable
private fun QuickConnectForm(
    pin: String?,
    isLoading: Boolean,
    isWaiting: Boolean,
    error: String?,
    onInitiate: () -> Unit,
    onCancel: () -> Unit,
) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        if (pin != null) {
            Text("Digite este código no servidor:", style = MaterialTheme.typography.bodyMedium, color = Color.White)
            Text(
                text = pin,
                style = MaterialTheme.typography.displaySmall,
                color = Color(0xFF00A4DC),
                fontWeight = FontWeight.Bold,
                letterSpacing = 8.sp
            )
            if (isWaiting) {
                CircularProgressIndicator(color = Color(0xFF00A4DC))
                Text("Aguardando autorização...", color = Color.White.copy(0.7f))
            }
            OutlinedButton(onClick = onCancel) { Text("Cancelar") }
        } else {
            Icon(Icons.Default.QrCode2, contentDescription = null, tint = Color(0xFF00A4DC), modifier = Modifier.size(64.dp))
            Text("Gera um código de 6 dígitos para entrar sem senha.", style = MaterialTheme.typography.bodyMedium, color = Color.White.copy(0.8f))
            error?.let { Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall) }
            Button(onClick = onInitiate, enabled = !isLoading, modifier = Modifier.fillMaxWidth().height(52.dp), shape = RoundedCornerShape(12.dp)) {
                if (isLoading) CircularProgressIndicator(modifier = Modifier.size(20.dp), color = Color.White, strokeWidth = 2.dp)
                else Text("Gerar Código Quick Connect")
            }
        }
    }
}

@Composable
private fun UserAvatarRow(
    users: List<org.mulletaflix.domain.model.UserInfo>,
    onUserSelect: (org.mulletaflix.domain.model.UserInfo) -> Unit,
) {
    // TODO: render user avatar row with coil images
}

private val Int.sp get() = androidx.compose.ui.unit.TextUnit(this.toFloat(), androidx.compose.ui.unit.TextUnitType.Sp)
