// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MediaBrowser.Common.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Net.Http.Headers;
using MulletaFlix.Data.Enums;
using MediaBrowser.Common.Configuration;
using MediaBrowser.Controller;
using MediaBrowser.Controller.Entities;
using MediaBrowser.Controller.Library;
using MediaBrowser.Controller.LiveTv;
using MediaBrowser.Model.Activity;
using MulletaFlix.Database.Implementations.Entities;
using MediaBrowser.Model.Configuration;
using MediaBrowser.Model.Entities;
using MediaBrowser.Model.LiveTv;
using MediaBrowser.Providers.Plugins.MidiaStorageOnline.Configuration;

namespace MediaBrowser.Providers.Plugins.MidiaStorageOnline.Api
{
    [ApiController]
    [Authorize]
    [Route("[controller]")]
    [Produces(MediaTypeNames.Application.Json)]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class MidiaStorageOnlineController : ControllerBase
    {
        private const int MaxMovieFolderNameLength = 96;
        private const int MaxMovieFileStemLength = 120;
        private const int MaxSeriesShowNameLength = 96;
        private const int MaxSeasonFolderNameLength = 48;
        private const int MaxEpisodeFileStemLength = 120;

        // BG-1: bounded parallelism â€” ProcessorCount*2 vs old 256
        private static readonly int _maxParallelism = Math.Max(4, Environment.ProcessorCount * 2);

        // BG-2: allocate once, not per-entry
        private static readonly char[] _invalidFileNameChars = Path.GetInvalidFileNameChars();

        // BG-3: compiled regex â€” reused across all entries
        private static readonly Regex _epRegex = new(
            @"^(.*?)\s+S(\d+)\s*E(\d+)(?:\s+(.*))?$",
            RegexOptions.IgnoreCase | RegexOptions.Compiled);

        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfigurationManager _configurationManager;
        private readonly IServerApplicationHost _serverApplicationHost;
        private readonly ILibraryMonitor _libraryMonitor;
        private readonly ITunerHostManager _tunerHostManager;
        private readonly ILibraryManager _libraryManager;
        private readonly IActivityManager _activityManager;
        private readonly ILogger<MidiaStorageOnlineController> _logger;

        public MidiaStorageOnlineController(
            IHttpClientFactory httpClientFactory,
            IConfigurationManager configurationManager,
            IServerApplicationHost serverApplicationHost,
            ILibraryMonitor libraryMonitor,
            ITunerHostManager tunerHostManager,
            ILibraryManager libraryManager,
            IActivityManager activityManager,
            ILogger<MidiaStorageOnlineController> logger)
        {
            _httpClientFactory = httpClientFactory;
            _configurationManager = configurationManager;
            _serverApplicationHost = serverApplicationHost;
            _libraryMonitor = libraryMonitor;
            _tunerHostManager = tunerHostManager;
            _libraryManager = libraryManager;
            _activityManager = activityManager;
            _logger = logger;
        }

        private void Log(string msg)
        {
            _logger.LogInformation("{Msg}", msg);
        }

        private PluginConfiguration GetConfig() => _configurationManager.GetConfiguration<PluginConfiguration>("midiastorageonline");
        private void SaveConfig(PluginConfiguration config) => _configurationManager.SaveConfiguration("midiastorageonline", config);

        [HttpPost("config")]
        public IActionResult SavePluginConfig([FromBody] PluginConfiguration body)
        {
            var config = GetConfig();
            config.UseWorldStorage = body.UseWorldStorage;
            config.M3uUrl = body.M3uUrl;
            config.EpgUrl = body.EpgUrl;
            config.EnableAutoEpg = body.EnableAutoEpg;
            config.AutoEpgLanguage = body.AutoEpgLanguage;
            config.MaxLinkValidationConcurrency = body.MaxLinkValidationConcurrency;
            config.StrmOutputPath = body.StrmOutputPath;
            config.OutputMode = body.OutputMode;
            SaveConfig(config);
            Log("Configuracao salva via MidiaStorageOnline/config.");
            return NoContent();
        }

        [HttpGet("status")]
        public IActionResult GetStatus()
        {
            var config = GetConfig();
            Log("Status consultado.");
            return Ok(new
            {
                m3uUrl = string.IsNullOrEmpty(config.M3uUrl) ? null : config.M3uUrl,
                strmPath = config.StrmOutputPath ?? GetDefaultStrmPath(),
                hasCanais = !string.IsNullOrEmpty(config.CanaisM3uContent),
                epgUrl = string.IsNullOrEmpty(config.EpgUrl) ? null : config.EpgUrl,
                epgGuidePath = System.IO.File.Exists(GetGuideFilePath()) ? GetGuideFilePath() : null,
                epgGuideUrl = System.IO.File.Exists(GetGuideFilePath()) ? $"{Request.Scheme}://{Request.Host}/MidiaStorageOnline/epg/guide.xml" : null,
                lastSync = config.LastSyncTime,
                lastSyncDuration = config.LastSyncDurationSeconds,
                syncedFileCount = config.SyncedFileCount,
                totalChannelCount = config.TotalChannelCount,
                epgCompatibleChannelCount = config.EpgCompatibleChannelCount,
                epgLastSyncTime = config.EpgLastSyncTime,
                epgLastError = config.EpgLastError,
                lastError = config.LastSyncError
            });
        }

        [AllowAnonymous]
        [HttpGet("m3u/canais")]
        public IActionResult GetCanaisM3U()
        {
            // BG-5: serve from dedicated file, not from config.xml
            var canaisFile = GetCanaisFilePath();
            if (!System.IO.File.Exists(canaisFile))
            {
                var config = GetConfig();
                if (!string.IsNullOrWhiteSpace(config.CanaisM3uContent))
                {
                    try
                    {
                        Directory.CreateDirectory(Path.GetDirectoryName(canaisFile)!);
                        System.IO.File.WriteAllText(canaisFile, config.CanaisM3uContent);
                        Log("M3U canais recriado a partir da configuracao em memoria.");
                    }
                    catch (Exception ex)
                    {
                        Log($"Falha ao recriar M3U canais a partir da configuracao: {ex.Message}");
                    }
                }

                if (!System.IO.File.Exists(canaisFile))
                {
                    Log("M3U canais requisitado mas arquivo nao encontrado.");
                    return NotFound("Nenhum dado de canais. Execute sincronizar primeiro.");
                }
            }
            var content = System.IO.File.ReadAllText(canaisFile);
            Log($"M3U canais servido ({content.Length / 1024}KB).");
            return Content(content, "application/x-mpegurl");
        }

        [AllowAnonymous]
        [HttpGet("logos/{fileName}")]
        public IActionResult GetLogo(string fileName)
        {
            if (string.IsNullOrWhiteSpace(fileName))
            {
                return NotFound();
            }

            var safeFileName = Path.GetFileName(fileName);
            var logosDir = MidiaStorageOnlineLogoLibrary.GetLogoDirectory(_configurationManager.CommonApplicationPaths);
            var fullPath = Path.Combine(logosDir, safeFileName);
            if (!System.IO.File.Exists(fullPath))
            {
                return NotFound();
            }

            return PhysicalFile(fullPath, GetLogoContentType(fullPath));
        }

        [AllowAnonymous]
        [HttpGet("epg/guide.xml")]
        public IActionResult GetGuideXml()
        {
            var guideFile = GetGuideFilePath();
            if (!System.IO.File.Exists(guideFile))
            {
                Log("XMLTV requisitado mas arquivo nao encontrado.");
                return NotFound("Nenhum guia XMLTV foi sincronizado ainda.");
            }

            return PhysicalFile(guideFile, "application/xml");
        }

        [AllowAnonymous]
        [HttpGet("stream")]
        [HttpHead("stream")]
        public async Task<IActionResult> ProxyStream([FromQuery(Name = "u")] string encodedUrl, CancellationToken cancellationToken)
        {
            if (!MidiaStorageOnlineStreamProxy.TryGetUpstreamUri(encodedUrl, out var upstreamUri))
            {
                return BadRequest("URL de mídia inválida.");
            }

            using var requestMessage = new HttpRequestMessage(HttpMethod.Get, upstreamUri);
            requestMessage.Headers.TryAddWithoutValidation(HeaderNames.UserAgent, MidiaStorageOnlineStreamProxy.GetBrowserUserAgent());
            requestMessage.Headers.TryAddWithoutValidation(HeaderNames.Accept, "*/*");
            requestMessage.Headers.TryAddWithoutValidation(HeaderNames.Referer, $"{upstreamUri.Scheme}://{upstreamUri.Host}/");
            requestMessage.Headers.TryAddWithoutValidation(HeaderNames.Origin, $"{upstreamUri.Scheme}://{upstreamUri.Host}");

            var rangeValue = Request.Headers[HeaderNames.Range].ToString();
            if (!string.IsNullOrWhiteSpace(rangeValue))
            {
                requestMessage.Headers.TryAddWithoutValidation(HeaderNames.Range, rangeValue);
            }

            using var client = _httpClientFactory.CreateClient(NamedClient.Default);
            client.Timeout = TimeSpan.FromSeconds(120);
            using var upstreamResponse = await client
                .SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead, cancellationToken)
                .ConfigureAwait(false);

            Response.StatusCode = (int)upstreamResponse.StatusCode;

            if (upstreamResponse.Content.Headers.ContentType is not null)
            {
                Response.ContentType = upstreamResponse.Content.Headers.ContentType.ToString();
            }
            else
            {
                Response.ContentType = "application/octet-stream";
            }

            if (upstreamResponse.Headers.TryGetValues(HeaderNames.AcceptRanges, out var acceptRanges))
            {
                Response.Headers[HeaderNames.AcceptRanges] = string.Join(", ", acceptRanges);
            }

            if (upstreamResponse.Content.Headers.ContentRange is not null)
            {
                Response.Headers[HeaderNames.ContentRange] = upstreamResponse.Content.Headers.ContentRange.ToString();
            }

            if (upstreamResponse.Content.Headers.ContentLength.HasValue)
            {
                Response.ContentLength = upstreamResponse.Content.Headers.ContentLength.Value;
            }

            if (HttpMethods.IsHead(Request.Method))
            {
                return new EmptyResult();
            }

            await using var upstreamStream = await upstreamResponse.Content.ReadAsStreamAsync(cancellationToken).ConfigureAwait(false);
            await upstreamStream.CopyToAsync(Response.Body, cancellationToken).ConfigureAwait(false);
            return new EmptyResult();
        }

        private string GetDataDir()
        {
            return Path.Combine(_configurationManager.CommonApplicationPaths.ProgramDataPath, "midia-online");
        }

        private string GetCanaisFilePath()
        {
            return Path.Combine(GetDataDir(), "canais.m3u8");
        }

        private string GetGuideFilePath()
        {
            return Path.Combine(GetDataDir(), "guide.xml");
        }

        private string GetOfflineLinkCachePath()
        {
            return Path.Combine(GetDataDir(), "offline-links.json");
        }

        private static string GetLogoContentType(string path)
        {
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return ext switch
            {
                ".jpg" or ".jpeg" => "image/jpeg",
                ".png" => "image/png",
                ".gif" => "image/gif",
                ".webp" => "image/webp",
                ".svg" => "image/svg+xml",
                _ => "application/octet-stream"
            };
        }

        private async Task UpdateLiveTvChannelItemsAsync(IEnumerable<M3uEntry> entries, CancellationToken ct)
        {
            var logoByName = entries
                .Where(e => e.Type == "Canal")
                .Where(e => !string.IsNullOrWhiteSpace(e.TvgLogo))
                .GroupBy(e => NormalizeChannelDisplayName(e.Name), StringComparer.OrdinalIgnoreCase)
                .ToDictionary(g => g.Key, g => g.First().TvgLogo!, StringComparer.OrdinalIgnoreCase);

            var channelItems = _libraryManager.GetItemList(new InternalItemsQuery
            {
                IncludeItemTypes = new[] { BaseItemKind.LiveTvChannel }
            });

            foreach (var baseItem in channelItems)
            {
                ct.ThrowIfCancellationRequested();

                if (baseItem is not LiveTvChannel channelItem)
                {
                    continue;
                }

                var normalizedName = NormalizeChannelDisplayName(channelItem.Name);
                var changed = false;

                if (!string.Equals(channelItem.Name, normalizedName, StringComparison.Ordinal))
                {
                    channelItem.Name = normalizedName;
                    changed = true;
                }

                if (!string.Equals(channelItem.ForcedSortName, normalizedName, StringComparison.Ordinal))
                {
                    channelItem.ForcedSortName = normalizedName;
                    changed = true;
                }

                if (logoByName.TryGetValue(normalizedName, out var localLogoUrl)
                    && !string.IsNullOrWhiteSpace(localLogoUrl))
                {
                    var currentImagePath = channelItem.GetImages(ImageType.Primary).FirstOrDefault()?.Path;
                    if (!string.Equals(currentImagePath, localLogoUrl, StringComparison.OrdinalIgnoreCase))
                    {
                        channelItem.SetImagePath(ImageType.Primary, localLogoUrl);
                        changed = true;
                    }
                }

                if (changed)
                {
                    await _libraryManager.UpdateItemAsync(channelItem, channelItem.GetParent(), ItemUpdateType.MetadataImport, ct).ConfigureAwait(false);
                }
            }
        }

        private static string NormalizeChannelDisplayName(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return string.Empty;
            }

            var cleaned = Regex.Replace(name.Trim(), @"^\s*\d+\s*(?:[-:]\s*)?", string.Empty, RegexOptions.CultureInvariant);
            cleaned = Regex.Replace(cleaned, @"\s{2,}", " ");
            cleaned = cleaned.Trim();

            return string.IsNullOrWhiteSpace(cleaned) ? name.Trim() : cleaned;
        }

        private async Task<string?> EnsureEpgGuideAsync(PluginConfiguration config, List<string> m3uEpgUrls, CancellationToken ct)
        {
            var epgUrls = new List<string>(m3uEpgUrls);

            if (!string.IsNullOrWhiteSpace(config.EpgUrl))
            {
                var customUrls = config.EpgUrl.Split(new[] { ',', ';' }, StringSplitOptions.RemoveEmptyEntries)
                    .Select(u => u.Trim())
                    .Where(u => Uri.TryCreate(u, UriKind.Absolute, out var uri) && uri.Scheme.StartsWith("http", StringComparison.OrdinalIgnoreCase));
                epgUrls.AddRange(customUrls);
            }

            epgUrls = epgUrls.Distinct(StringComparer.OrdinalIgnoreCase).ToList();

            if (epgUrls.Count == 0)
            {
                return null;
            }

            var guidePath = GetGuideFilePath();
            var guideDir = Path.GetDirectoryName(guidePath)!;
            Directory.CreateDirectory(guideDir);

            var channelNodes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var programmeNodes = new List<string>();
            var sourcesLoaded = 0;

            foreach (var url in epgUrls)
            {
                ct.ThrowIfCancellationRequested();
                try
                {
                    Log($"Baixando EPG de: {url}");
                    var xml = await DownloadEpgXmlAsync(url, ct).ConfigureAwait(false);
                    if (string.IsNullOrWhiteSpace(xml))
                    {
                        continue;
                    }

                    var xmlDoc = new XmlDocument();
                    xmlDoc.LoadXml(xml);

                    var channels = xmlDoc.SelectNodes("//channel");
                    if (channels is not null)
                    {
                        foreach (XmlNode chNode in channels)
                        {
                            var idAttr = chNode.Attributes?["id"]?.Value;
                            if (!string.IsNullOrEmpty(idAttr))
                            {
                                channelNodes[idAttr] = chNode.OuterXml;
                            }
                        }
                    }

                    var programmes = xmlDoc.SelectNodes("//programme");
                    if (programmes is not null)
                    {
                        foreach (XmlNode prog in programmes)
                        {
                            programmeNodes.Add(prog.OuterXml);
                        }
                    }

                    sourcesLoaded++;
                }
                catch (Exception ex)
                {
                    Log($"Falha ao processar EPG de {url}: {ex.Message}");
                }
            }

            if (sourcesLoaded == 0)
            {
                throw new InvalidOperationException("Nenhum dado de EPG pode ser obtido de nenhuma das fontes.");
            }

            var mergedXml = new StringBuilder();
            mergedXml.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            mergedXml.AppendLine("<!DOCTYPE tv SYSTEM \"xmltv.dtd\">");
            mergedXml.AppendLine("<tv>");

            foreach (var chXml in channelNodes.Values)
            {
                mergedXml.AppendLine(chXml);
            }

            foreach (var progXml in programmeNodes)
            {
                mergedXml.AppendLine(progXml);
            }

            mergedXml.AppendLine("</tv>");

            var mergedContent = mergedXml.ToString();

            var guideXmlTempPath = guidePath + ".new";
            if (System.IO.File.Exists(guideXmlTempPath))
            {
                try { System.IO.File.Delete(guideXmlTempPath); } catch { }
            }

            await System.IO.File.WriteAllTextAsync(guideXmlTempPath, mergedContent, ct).ConfigureAwait(false);

            try
            {
                if (System.IO.File.Exists(guidePath))
                {
                    System.IO.File.Replace(guideXmlTempPath, guidePath, null, true);
                }
                else
                {
                    System.IO.File.Move(guideXmlTempPath, guidePath);
                }
            }
            catch
            {
                if (System.IO.File.Exists(guideXmlTempPath))
                {
                    System.IO.File.Copy(guideXmlTempPath, guidePath, true);
                    try { System.IO.File.Delete(guideXmlTempPath); } catch { }
                }
            }

            config.EpgLastSyncTime = DateTime.UtcNow;
            config.EpgLastError = null;
            return guidePath;
        }

        private async Task<string?> DownloadEpgXmlAsync(string url, CancellationToken ct, int maxRetries = 2)
        {
            for (int i = 0; i <= maxRetries; i++)
            {
                try
                {
                    using var client = _httpClientFactory.CreateClient();
                    client.Timeout = TimeSpan.FromSeconds(120);
                    client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
                    
                    var response = await client.GetAsync(url, ct).ConfigureAwait(false);
                    response.EnsureSuccessStatusCode();

                    var isGzip = url.EndsWith(".gz", StringComparison.OrdinalIgnoreCase) ||
                                 (response.Content.Headers.ContentType?.MediaType?.IndexOf("gzip", StringComparison.OrdinalIgnoreCase) >= 0) ||
                                 (response.Content.Headers.ContentEncoding?.Any(x => x.IndexOf("gzip", StringComparison.OrdinalIgnoreCase) >= 0) ?? false);

                    using var stream = await response.Content.ReadAsStreamAsync(ct).ConfigureAwait(false);
                    if (isGzip)
                    {
                        using var decompressed = new System.IO.Compression.GZipStream(stream, System.IO.Compression.CompressionMode.Decompress);
                        using var reader = new StreamReader(decompressed, Encoding.UTF8);
                        return await reader.ReadToEndAsync(ct).ConfigureAwait(false);
                    }
                    else
                    {
                        using var reader = new StreamReader(stream, Encoding.UTF8);
                        return await reader.ReadToEndAsync(ct).ConfigureAwait(false);
                    }
                }
                catch (Exception ex) when (i < maxRetries)
                {
                    Log($"Download de EPG falhou (tentativa {i + 1}/{maxRetries + 1}): {ex.Message}. Retentando...");
                    await Task.Delay(2000 * (i + 1), ct).ConfigureAwait(false);
                }
            }
            return null;
        }

        private List<string> ExtractEpgUrlsFromM3u(string m3uContent)
        {
            var urls = new List<string>();
            if (string.IsNullOrEmpty(m3uContent)) return urls;

            var lines = m3uContent.Split('\n');
            if (lines.Length > 0 && lines[0].StartsWith("#EXTM3U", StringComparison.OrdinalIgnoreCase))
            {
                var headerLine = lines[0];
                var matches = Regex.Matches(headerLine, @"(?:url-tvg|x-tvg-url)\s*=\s*""([^""]+)""", RegexOptions.IgnoreCase);
                foreach (Match match in matches)
                {
                    var val = match.Groups[1].Value;
                    var parts = val.Split(new[] { ',', ';', ' ' }, StringSplitOptions.RemoveEmptyEntries);
                    foreach (var part in parts)
                    {
                        var trimmedPart = part.Trim();
                        if (Uri.TryCreate(trimmedPart, UriKind.Absolute, out var uri) && uri.Scheme.StartsWith("http", StringComparison.OrdinalIgnoreCase))
                        {
                            urls.Add(trimmedPart);
                        }
                    }
                }
            }
            return urls;
        }

        private async Task<string?> AutoFetchEpgAsync(PluginConfiguration config, List<M3uEntry> entries, CancellationToken ct)
        {
            var channelEntries = entries
                .Where(e => e.Type == "Canal")
                .ToList();

            if (channelEntries.Count == 0)
            {
                Log("Auto EPG: nenhum canal encontrado no M3U.");
                return null;
            }

            var dataDir = GetDataDir();
            var channelsXmlPath = Path.Combine(dataDir, "channels.xml");
            var guideXmlPath = Path.Combine(dataDir, "guide.xml");
            var guideXmlTempPath = Path.Combine(dataDir, "guide.xml.new");

            Directory.CreateDirectory(dataDir);

            try
            {
                var guidesJsonPath = Path.Combine(dataDir, "guides.json");
                var needDownloadGuides = true;
                if (System.IO.File.Exists(guidesJsonPath))
                {
                    var fileInfo = new FileInfo(guidesJsonPath);
                    if (DateTime.UtcNow - fileInfo.LastWriteTimeUtc < TimeSpan.FromHours(24) && fileInfo.Length > 0)
                    {
                        needDownloadGuides = false;
                    }
                }

                if (needDownloadGuides)
                {
                    Log("Auto EPG: Baixando guides.json da iptv-org...");
                    var guidesJsonContent = await DownloadStringWithRetryAsync("https://iptv-org.github.io/api/guides.json", ct).ConfigureAwait(false);
                    if (string.IsNullOrEmpty(guidesJsonContent))
                    {
                        throw new InvalidOperationException("Falha ao baixar guides.json da iptv-org.");
                    }

                    await System.IO.File.WriteAllTextAsync(guidesJsonPath, guidesJsonContent, ct).ConfigureAwait(false);
                }

                var guidesJson = await System.IO.File.ReadAllTextAsync(guidesJsonPath, ct).ConfigureAwait(false);
                using var doc = JsonDocument.Parse(guidesJson);
                var catalog = MidiaStorageOnlineEpgMapper.BuildCatalog(channelEntries, doc);

                if (catalog.Channels.Count == 0)
                {
                    Log("Auto EPG: nenhum canal encontrado no guides.json da iptv-org.");
                    return null;
                }

                Log($"Auto EPG: {catalog.UniqueChannelCount} canais unicos resolvidos. Guia: {catalog.GuideMatchCount}, overrides: {catalog.OverrideCount}, sinteticos: {catalog.SyntheticCount}.");

                var xmlSettings = new XmlWriterSettings
                {
                    Indent = true,
                    Encoding = Encoding.UTF8
                };

                using (var writer = XmlWriter.Create(channelsXmlPath, xmlSettings))
                {
                    writer.WriteStartDocument();
                    writer.WriteStartElement("channels");

                    foreach (var ch in catalog.Channels)
                    {
                        writer.WriteStartElement("channel");
                        writer.WriteAttributeString("site", ch.Site);
                        writer.WriteAttributeString("site_id", ch.SiteId);
                        writer.WriteAttributeString("lang", ch.Lang);
                        writer.WriteAttributeString("xmltv_id", ch.XmltvId);
                        writer.WriteValue(ch.DisplayName);
                        writer.WriteEndElement();
                    }

                    writer.WriteEndElement();
                    writer.WriteEndDocument();
                }

                var guideUrls = catalog.Channels
                    .Where(ch => !string.IsNullOrWhiteSpace(ch.Site) && !string.IsNullOrWhiteSpace(ch.Lang))
                    .Select(ch => new { Lang = ch.Lang.ToLowerInvariant(), Site = ch.Site.ToLowerInvariant() })
                    .Distinct()
                    .Select(x => $"https://iptv-org.github.io/epg/guides/{x.Lang}/{x.Site}.epg.xml")
                    .ToList();

                if (guideUrls.Count == 0)
                {
                    Log("Auto EPG: nenhuma URL de guia encontrada para os canais resolvidos.");
                    return null;
                }

                Log($"Auto EPG: Baixando {guideUrls.Count} fontes de guia XMLTV...");
                var channelNodes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                var programmeNodes = new List<string>();

                var sourcesLoaded = 0;
                foreach (var guideUrl in guideUrls)
                {
                    ct.ThrowIfCancellationRequested();
                    try
                    {
                        var xml = await DownloadEpgXmlAsync(guideUrl, ct, maxRetries: 1).ConfigureAwait(false);
                        if (string.IsNullOrWhiteSpace(xml))
                        {
                            continue;
                        }

                        var xmlDoc = new XmlDocument();
                        xmlDoc.LoadXml(xml);

                        MidiaStorageOnlineEpgXmlMerger.AddDocument(xmlDoc, catalog.Channels, channelNodes, programmeNodes);

                        sourcesLoaded++;
                    }
                    catch (Exception srcEx)
                    {
                        Log($"Auto EPG: Falha ao baixar guia {guideUrl}: {srcEx.Message}");
                    }
                }

                var mergedXml = new StringBuilder();
                mergedXml.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                mergedXml.AppendLine("<!DOCTYPE tv SYSTEM \"xmltv.dtd\">");
                mergedXml.AppendLine("<tv>");

                foreach (var chXml in channelNodes.Values)
                {
                    mergedXml.AppendLine(chXml);
                }

                foreach (var progXml in programmeNodes)
                {
                    mergedXml.AppendLine(progXml);
                }

                mergedXml.AppendLine("</tv>");

                var mergedContent = mergedXml.ToString();
                if (sourcesLoaded == 0 || mergedContent.Length < 500)
                {
                    throw new InvalidOperationException("Auto EPG: Nenhum dado de programa obtido das fontes.");
                }

                if (System.IO.File.Exists(guideXmlTempPath))
                {
                    try { System.IO.File.Delete(guideXmlTempPath); } catch { }
                }

                await System.IO.File.WriteAllTextAsync(guideXmlTempPath, mergedContent, ct).ConfigureAwait(false);

                try
                {
                    if (System.IO.File.Exists(guideXmlPath))
                    {
                        System.IO.File.Replace(guideXmlTempPath, guideXmlPath, null, true);
                    }
                    else
                    {
                        System.IO.File.Move(guideXmlTempPath, guideXmlPath);
                    }
                }
                catch
                {
                    if (System.IO.File.Exists(guideXmlTempPath))
                    {
                        System.IO.File.Copy(guideXmlTempPath, guideXmlPath, true);
                        try { System.IO.File.Delete(guideXmlTempPath); } catch { }
                    }
                }

                var finalGuideInfo = new FileInfo(guideXmlPath);
                Log($"Auto EPG: Guia XMLTV gerado com sucesso: {finalGuideInfo.Length / 1024} KB de {sourcesLoaded} fontes.");
                config.EpgLastSyncTime = DateTime.UtcNow;
                config.EpgLastError = null;
                return guideXmlPath;
            }
            catch (Exception ex)
            {
                Log($"Auto EPG erro: {ex.Message}");
                config.EpgLastError = ex.Message;
                return null;
            }
        }

        private static int GetSitePriority(string? site)
        {
            if (string.IsNullOrEmpty(site)) return 0;
            site = site.ToLowerInvariant();
            if (site == "mi.tv") return 10;
            if (site == "claro.com.br") return 8;
            if (site == "sky.com.br") return 6;
            if (site == "meuguia.tv") return 4;
            return 1;
        }

        private async Task<string?> DownloadStringWithRetryAsync(string url, CancellationToken ct, int maxRetries = 2)
        {
            for (int i = 0; i <= maxRetries; i++)
            {
                try
                {
                    using var client = _httpClientFactory.CreateClient();
                    client.Timeout = TimeSpan.FromSeconds(60);
                    client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
                    return await client.GetStringAsync(url, ct).ConfigureAwait(false);
                }
                catch (Exception ex) when (i < maxRetries)
                {
                    Log($"Download falhou (tentativa {i + 1}/{maxRetries + 1}): {ex.Message}. Retentando...");
                    await Task.Delay(1000 * (i + 1), ct).ConfigureAwait(false);
                }
            }
            return null;
        }

        private class MappedChannel
        {
            public string Site { get; set; } = "";
            public string SiteId { get; set; } = "";
            public string Lang { get; set; } = "pt";
            public string XmltvId { get; set; } = "";
            public string Name { get; set; } = "";
        }

        private void RegisterXmlTvListingProvider(string guidePath, PluginConfiguration config)
        {
            var liveTvConfig = _configurationManager.GetConfiguration<LiveTvOptions>("livetv");
            var providers = liveTvConfig.ListingProviders.ToList();

            // Remove any old/conflicting iptv-org or duplicate providers
            providers.RemoveAll(p => p.Type == "iptvorg" || string.Equals(p.ListingsId, "iptv-org", StringComparison.OrdinalIgnoreCase));

            var provider = providers.FirstOrDefault(p =>
                string.Equals(p.Id, config.EpgListingProviderId, StringComparison.OrdinalIgnoreCase)
                || string.Equals(p.ListingsId, "Midia Storage Online EPG", StringComparison.OrdinalIgnoreCase));

            if (provider is null)
            {
                provider = new ListingsProviderInfo
                {
                    Id = Guid.NewGuid().ToString("N"),
                    Type = "xmltv"
                };
                providers.Add(provider);
            }

            provider.Type = "xmltv";
            provider.ListingsId = "Midia Storage Online EPG";
            provider.Path = guidePath;
            provider.EnableAllTuners = true;
            provider.EnabledTuners = Array.Empty<string>();
            provider.PreferredLanguage = "pt-BR";
            config.EpgListingProviderId = provider.Id;

            liveTvConfig.ListingProviders = providers.ToArray();
            _configurationManager.SaveConfiguration("livetv", liveTvConfig);
        }

        private static readonly object ManifestLock = new object();

        private Dictionary<string, string> LoadManifest()
        {
            var dir = GetDataDir();
            var path = Path.Combine(dir, "sync_manifest.json");
            lock (ManifestLock)
            {
                if (!System.IO.File.Exists(path))
                    return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                try
                {
                    var json = System.IO.File.ReadAllText(path);
                    return System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, string>>(json) 
                           ?? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                }
                catch (Exception ex)
                {
                    Log($"Erro ao carregar manifesto: {ex.Message}. Criando novo.");
                    return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                }
            }
        }

        private void SaveManifest(Dictionary<string, string> manifest)
        {
            var dir = GetDataDir();
            Directory.CreateDirectory(dir);
            var path = Path.Combine(dir, "sync_manifest.json");
            lock (ManifestLock)
            {
                try
                {
                    var json = System.Text.Json.JsonSerializer.Serialize(manifest, new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
                    System.IO.File.WriteAllText(path, json);
                }
                catch (Exception ex)
                {
                    Log($"Erro ao salvar manifesto: {ex.Message}");
                }
            }
        }

        private void NormalizeMidiaStorageOnlineTunerHost(string tunerUrl, string tunerId)
        {
            var liveTvConfig = _configurationManager.GetConfiguration<LiveTvOptions>("livetv");
            var tunerHosts = liveTvConfig.TunerHosts.ToList();
            var matchingHosts = tunerHosts
                .Where(h =>
                    string.Equals(h.Type, "m3u", StringComparison.OrdinalIgnoreCase)
                    && string.Equals(h.Url, tunerUrl, StringComparison.OrdinalIgnoreCase)
                    && string.Equals(h.FriendlyName, "Midia Storage Online (Canais)", StringComparison.OrdinalIgnoreCase))
                .ToList();

            if (matchingHosts.Count == 0)
            {
                return;
            }

            var primary = matchingHosts.FirstOrDefault(h => string.Equals(h.Id, tunerId, StringComparison.OrdinalIgnoreCase)) ?? matchingHosts[0];
            primary.Id = tunerId;
            primary.Type = "m3u";
            primary.Url = tunerUrl;
            primary.FriendlyName = "Midia Storage Online (Canais)";
            primary.TunerCount = 0;
            primary.AllowHWTranscoding = true;
            primary.AllowStreamSharing = true;
            primary.EnableStreamLooping = false;
            primary.AllowFmp4TranscodingContainer = false;
            primary.FallbackMaxStreamingBitrate = 30000000;
            primary.IgnoreDts = true;
            primary.ReadAtNativeFramerate = false;

            var normalizedHosts = tunerHosts
                .Where(h =>
                    !(string.Equals(h.Type, "m3u", StringComparison.OrdinalIgnoreCase)
                      && string.Equals(h.Url, tunerUrl, StringComparison.OrdinalIgnoreCase)
                      && string.Equals(h.FriendlyName, "Midia Storage Online (Canais)", StringComparison.OrdinalIgnoreCase)))
                .ToList();
            normalizedHosts.Add(primary);
            liveTvConfig.TunerHosts = normalizedHosts.ToArray();
            _configurationManager.SaveConfiguration("livetv", liveTvConfig);
        }

        [HttpPost("sync")]
        public async Task<IActionResult> Sync([FromQuery] bool force = false, CancellationToken ct = default)
        {
            var config = GetConfig();
            if (!HasPlaylistSource(config))
            {
                Log("Sync falhou: nenhuma origem M3U configurada.");
                return BadRequest(new { error = "Ative storage mundial ou informe uma URL da lista M3U." });
            }

            try
            {
                var sw = System.Diagnostics.Stopwatch.StartNew();
                Log(config.UseWorldStorage && string.IsNullOrWhiteSpace(config.M3uUrl)
                    ? "Iniciando sync: baixando M3U do storage mundial"
                    : $"Iniciando sync: baixando M3U de {config.M3uUrl}");
                MidiaStorageOnlineStreamProxy.LocalBaseUrl = _serverApplicationHost.GetSmartApiUrl(Request);
                string m3uRaw = null!;
                if (config.UseWorldStorage && string.IsNullOrWhiteSpace(config.M3uUrl))
                {
                    m3uRaw = await MidiaStorageOnlineWorldStorageDownloader.DownloadCombinedPlaylistAsync(_httpClientFactory, _logger, ct).ConfigureAwait(false);
                    Log($"M3U mundial baixado: {m3uRaw.Length / 1024}KB");
                }
                else
                {
                    for (var attempt = 0; attempt <= 2; attempt++)
                    {
                        try
                        {
                            using var httpClient = _httpClientFactory.CreateClient();
                            httpClient.Timeout = TimeSpan.FromMinutes(5);
                            httpClient.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
                            var resp = await httpClient.GetAsync(config.M3uUrl!).ConfigureAwait(false);
                            if (!resp.IsSuccessStatusCode)
                            {
                                Log($"Falha ao baixar M3U: HTTP {resp.StatusCode}");
                                if (attempt < 2)
                                {
                                    await Task.Delay(2000 * (attempt + 1)).ConfigureAwait(false);
                                    continue;
                                }
                                return BadRequest(new { error = $"Falha ao baixar M3U: HTTP {resp.StatusCode}" });
                            }
                            var bytes = await resp.Content.ReadAsByteArrayAsync().ConfigureAwait(false);
                            m3uRaw = Encoding.UTF8.GetString(bytes);
                            Log($"M3U baixado: {m3uRaw.Length / 1024}KB");
                            break;
                        }
                        catch (Exception ex) when (attempt < 2)
                        {
                            Log($"Download M3U falhou (tentativa {attempt + 1}/3): {ex.Message}. Retentando...");
                            await Task.Delay(2000 * (attempt + 1)).ConfigureAwait(false);
                        }
                    }
                }

                var entries = ParseM3u(m3uRaw, out var headerLine);
                var totalParsed = entries.Count;
                var channelCandidates = entries.Where(e => e.Type == "Canal").ToList();
                var mediaCandidates = entries.Where(e => e.Type == "Filme" || e.Type == "Serie").ToList();

                var channelEntries = (await MidiaStorageOnlineLinkValidator.FilterOnlineEntriesAsync(
                    channelCandidates,
                    _httpClientFactory,
                    _logger,
                    ct,
                    config.MaxLinkValidationConcurrency,
                    GetOfflineLinkCachePath()).ConfigureAwait(false)).ToList();
                if (channelEntries.Count != channelCandidates.Count)
                {
                    Log($"Links offline removidos dos canais antes do sync: {channelCandidates.Count - channelEntries.Count}");
                }
                channelEntries = MidiaStorageOnlineEntryDeduplicator.DeduplicateByKey(channelEntries, BuildEntryDedupKey).ToList();
                Log($"Canais validados: {channelEntries.Count} entradas ativas.");
                Log($"M3U parsed: {totalParsed} entradas");

                if (channelEntries.Count > 0)
                {
                    var s = channelEntries[0];
                    Log($"Amostra 1: [{s.Type}] {s.Name} | URL: {s.Url}");
                }
                if (channelEntries.Count > 1)
                {
                    var s = channelEntries[1];
                    Log($"Amostra 2: [{s.Type}] {s.Name} | URL: {s.Url}");
                }
                if (channelEntries.Count > 2)
                {
                    var s = channelEntries[2];
                    Log($"Amostra 3: [{s.Type}] {s.Name} | URL: {s.Url}");
                }

                // 1. Processar e cadastrar os canais imediatamente apÃ³s o parse do M3U
                try
                {
                    await MidiaStorageOnlineLogoLibrary.EnsureChannelLogosAsync(
                        channelEntries,
                        $"{Request.Scheme}://{Request.Host}",
                        _configurationManager.CommonApplicationPaths,
                        ct).ConfigureAwait(false);
                }
                catch (Exception logoEx)
                {
                    Log($"Falha ao resolver logos dos canais: {logoEx.Message}");
                }

                var canaisM3u = new StringBuilder();
                canaisM3u.Append(headerLine);
                foreach (var entry in channelEntries)
                {
                    AppendEntryLinesWithInferredTvgId(canaisM3u, entry);
                }

                // BG-5: save canais to dedicated file ONLY, do NOT serialize into config.xml
                var canaisContent = MidiaStorageOnlineStreamProxy.NormalizeM3uContent(canaisM3u.ToString());
                var canaisFilePath = GetCanaisFilePath();
                Directory.CreateDirectory(Path.GetDirectoryName(canaisFilePath)!);
                await System.IO.File.WriteAllTextAsync(canaisFilePath, canaisContent).ConfigureAwait(false);

                config.TotalChannelCount = channelEntries.Count;
                config.EpgCompatibleChannelCount = channelEntries.Count(e => !string.IsNullOrWhiteSpace(GetEffectiveTvgId(e)));

                // Cadastrar/atualizar sintonizador imediatamente
                var tunerUrl = $"{Request.Scheme}://{Request.Host}/MidiaStorageOnline/m3u/canais";
                var tuner = new TunerHostInfo
                {
                    Id = config.TunerHostId,
                    Type = "m3u",
                    Url = tunerUrl,
                    FriendlyName = "Midia Storage Online (Canais)",
                    TunerCount = 0,
                    AllowHWTranscoding = true
                };
                var saved = await _tunerHostManager.SaveTunerHost(tuner).ConfigureAwait(false);
                config.TunerHostId = saved.Id;
                NormalizeMidiaStorageOnlineTunerHost(tunerUrl, saved.Id);

                var epgConfigured = !string.IsNullOrWhiteSpace(config.EpgUrl);
                var m3uEpgUrls = ExtractEpgUrlsFromM3u(m3uRaw);
                if (config.EnableAutoEpg || epgConfigured || m3uEpgUrls.Count > 0)
                {
                    try
                    {
                        string? guidePath;
                        if (config.EnableAutoEpg)
                        {
                            guidePath = await AutoFetchEpgAsync(config, channelEntries, ct).ConfigureAwait(false);
                        }
                        else
                        {
                            guidePath = await EnsureEpgGuideAsync(config, m3uEpgUrls, ct).ConfigureAwait(false);
                        }
                        if (!string.IsNullOrEmpty(guidePath) && System.IO.File.Exists(guidePath))
                        {
                            RegisterXmlTvListingProvider(guidePath, config);
                        }
                    }
                    catch (Exception epgEx)
                    {
                        config.EpgLastError = epgEx.Message;
                        Log($"Falha ao sincronizar XMLTV/EPG: {epgEx.Message}");
                    }
                }
                else
                {
                    config.EpgLastError = null;
                }

                SaveConfig(config);
                Log($"Sintonizador M3U registrado no Live TV imediatamente: {tunerUrl} (ID: {saved.Id})");

                // 2. Criar pastas e preparar bibliotecas para filmes e series
                var strmPath = GetStrmOutputPath(config);
                var moviesPath = Path.Combine(strmPath, "Filmes");
                var seriesPath = Path.Combine(strmPath, "Series");

                Directory.CreateDirectory(moviesPath);
                Directory.CreateDirectory(seriesPath);
                _libraryMonitor.ReportFileSystemChangeBeginning(strmPath);

                try
                {
                    var validatedMediaEntries = (await MidiaStorageOnlineLinkValidator.FilterOnlineEntriesAsync(
                        mediaCandidates,
                        _httpClientFactory,
                        _logger,
                        ct,
                        config.MaxLinkValidationConcurrency,
                        GetOfflineLinkCachePath()).ConfigureAwait(false)).ToList();
                    if (validatedMediaEntries.Count != mediaCandidates.Count)
                    {
                        Log($"Links offline removidos das midias antes do sync: {mediaCandidates.Count - validatedMediaEntries.Count}");
                    }
                    validatedMediaEntries = MidiaStorageOnlineEntryDeduplicator.DeduplicateByKey(validatedMediaEntries, BuildEntryDedupKey).ToList();
                    Log($"Midias validadas: {validatedMediaEntries.Count} entradas ativas.");

                    // Count upfront to create libraries before file processing
                    int entryMovieCount = validatedMediaEntries.Count(e => e.Type == "Filme");
                    int entrySeriesCount = validatedMediaEntries.Count(e => e.Type == "Serie");

                var existingLibs = _libraryManager.GetVirtualFolders().Select(v => v.Name).ToHashSet();

                if (!existingLibs.Contains("Filmes"))
                {
                    await _libraryManager.AddVirtualFolder("Filmes", CollectionTypeOptions.movies,
                        new LibraryOptions
                        {
                            PathInfos = new[] { new MediaPathInfo(moviesPath) },
                            PreferredMetadataLanguage = "pt-BR",
                            MetadataCountryCode = "BR"
                        }, true).ConfigureAwait(false);
                    Log($"Biblioteca 'Filmes' criada apontando para {moviesPath}");
                }

                if (!existingLibs.Contains("Series") && entrySeriesCount > 0)
                {
                    await _libraryManager.AddVirtualFolder("Series", CollectionTypeOptions.tvshows,
                        new LibraryOptions
                        {
                            PathInfos = new[] { new MediaPathInfo(seriesPath) },
                            PreferredMetadataLanguage = "pt-BR",
                            MetadataCountryCode = "BR"
                        }, true).ConfigureAwait(false);
                    Log($"Biblioteca 'Series' criada apontando para {seriesPath}");
                }

                    var manifest = force ? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) : LoadManifest();
                    var newManifest = new System.Collections.Concurrent.ConcurrentDictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                    var createdDirs = new System.Collections.Concurrent.ConcurrentDictionary<string, byte>(StringComparer.OrdinalIgnoreCase);

                    var totalSynced = 0;
                    int movieCount = 0, seriesCount = 0, skippedCount = 0;

                // Loop paralelo somente para filmes e series
                    var movieAndSeriesEntries = validatedMediaEntries.Where(e => e.Type == "Filme" || e.Type == "Serie").ToList();

                // BG-1: bounded parallelism
                await Parallel.ForEachAsync(movieAndSeriesEntries, new ParallelOptions { MaxDegreeOfParallelism = _maxParallelism }, async (entry, ct) =>
                {
                    try
                    {
                        if (entry.Type == "Filme")
                        {
                            var name = TruncatePathSegment(SanitizeName(entry.Name), MaxMovieFolderNameLength);
                            // ponytail: hash only the .strm name to keep folder names readable and still avoid collisions.
                            var fileName = TrimPathSegment(SanitizeName(entry.Name), MaxMovieFileStemLength);
                            var relPath = Path.Combine("Filmes", name, fileName + ".strm");
                            var filePath = Path.Combine(strmPath, relPath);
                            var newUrl = entry.Url.Trim();

                            newManifest.TryAdd(relPath, newUrl);

                            var fileExists = System.IO.File.Exists(filePath);
                            if (fileExists)
                            {
                                try
                                {
                                    var existingUrl = (await System.IO.File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false)).Trim();
                                    if (existingUrl.Equals(newUrl, StringComparison.OrdinalIgnoreCase))
                                    {
                                        Interlocked.Increment(ref skippedCount);
                                        return;
                                    }
                                }
                                catch
                                {
                                    // Se falhar ao ler o arquivo, prossegue com a sobrescrita
                                }

                                Log($"Sobrescrevendo .strm: {filePath}");
                            }

                            var dir = Path.Combine(moviesPath, name);
                            if (createdDirs.TryAdd(dir, 0))
                            {
                                Directory.CreateDirectory(dir);
                            }
                            else if (!Directory.Exists(dir))
                            {
                                Directory.CreateDirectory(dir);
                            }
                            await System.IO.File.WriteAllTextAsync(filePath, newUrl, ct).ConfigureAwait(false);
                            Interlocked.Increment(ref totalSynced);
                            Interlocked.Increment(ref movieCount);
                        }
                        else if (entry.Type == "Serie")
                        {
                            var showName = TruncatePathSegment(SanitizeName(entry.ShowName), MaxSeriesShowNameLength);
                            var seasonFolder = TruncatePathSegment(SanitizeName(entry.Season), MaxSeasonFolderNameLength);
                            // ponytail: hash only the .strm name to keep folder names readable and still avoid collisions.
                            var fileName = TrimPathSegment(SanitizeName(entry.Name), MaxEpisodeFileStemLength);
                            var relPath = Path.Combine("Series", showName, seasonFolder, fileName + ".strm");
                            var filePath = Path.Combine(strmPath, relPath);
                            var newUrl = entry.Url.Trim();

                            newManifest.TryAdd(relPath, newUrl);

                            var fileExists = System.IO.File.Exists(filePath);
                            if (fileExists)
                            {
                                try
                                {
                                    var existingUrl = (await System.IO.File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false)).Trim();
                                    if (existingUrl.Equals(newUrl, StringComparison.OrdinalIgnoreCase))
                                    {
                                        Interlocked.Increment(ref skippedCount);
                                        return;
                                    }
                                }
                                catch
                                {
                                    // Se falhar ao ler o arquivo, prossegue com a sobrescrita
                                }

                                Log($"Sobrescrevendo .strm: {filePath}");
                            }

                            var dir = Path.Combine(seriesPath, showName, seasonFolder);
                            if (createdDirs.TryAdd(dir, 0))
                            {
                                Directory.CreateDirectory(dir);
                            }
                            else if (!Directory.Exists(dir))
                            {
                                Directory.CreateDirectory(dir);
                            }
                            await System.IO.File.WriteAllTextAsync(filePath, newUrl, ct).ConfigureAwait(false);
                            Interlocked.Increment(ref totalSynced);
                            Interlocked.Increment(ref seriesCount);
                        }
                    }
                    catch (Exception entryEx)
                    {
                        Log($"Falha ao processar entrada '{entry.Name}' no sync do controller: {entryEx}");
                    }
                }).ConfigureAwait(false);

                // Smart cleanup: delete files that are no longer in the M3U
                var filesToDelete = manifest.Keys.Except(newManifest.Keys).ToList();
                var deletedCount = 0;
                foreach (var relPath in filesToDelete)
                {
                    var filePath = Path.Combine(strmPath, relPath);
                    // BG-4: delete-then-catch is O(1) I/O vs exists-then-delete which is O(2n)
                    try
                    {
                        System.IO.File.Delete(filePath);
                        deletedCount++;
                        // Try to delete empty parent directories up to moviesPath / seriesPath
                        var dir = Path.GetDirectoryName(filePath);
                        while (dir != null && dir.Length > strmPath.Length && Directory.Exists(dir) && !Directory.EnumerateFileSystemEntries(dir).Any())
                        {
                            Directory.Delete(dir);
                            dir = Path.GetDirectoryName(dir);
                        }
                    }
                    catch (FileNotFoundException) { /* already gone, skip */ }
                    catch (Exception ex)
                    {
                        Log($"Erro ao deletar arquivo obsoleto {relPath}: {ex.Message}");
                    }
                }

                // Save manifest
                var manifestToSave = new Dictionary<string, string>(newManifest, StringComparer.OrdinalIgnoreCase);
                SaveManifest(manifestToSave);

                config.LastSyncTime = DateTime.UtcNow;
                config.LastSyncDurationSeconds = sw.Elapsed.TotalSeconds;
                config.SyncedFileCount = totalSynced;
                config.LastSyncError = null;
                SaveConfig(config);

                Log($"Sync OK em {sw.Elapsed.TotalSeconds:F1}s: {totalSynced} salvos, {skippedCount} ignorados, {deletedCount} deletados, canais M3U {canaisM3u.Length / 1024}KB");

                await _activityManager.CreateAsync(new ActivityLog(
                    $"{totalSynced} .strm criados ({movieCount} filmes, {seriesCount} series)",
                    "MidiaStorageOnlineSync",
                    Guid.Empty)
                {
                    Overview = $"{skippedCount} ignorados, {deletedCount} deletados. Canais M3U: {canaisM3u.Length / 1024}KB"
                }).ConfigureAwait(false);

                return Ok(new
                {
                    fileCount = totalSynced,
                    movieCount,
                    seriesCount,
                    skippedCount,
                    deletedCount,
                    canaisKb = canaisM3u.Length / 1024,
                    message = $"{totalSynced} .strm salvos, {skippedCount} ignorados, {deletedCount} deletados. Canais disponiveis no Dashboard > TV ao Vivo."
                });
                }
                finally
                {
                    _libraryMonitor.ReportFileSystemChangeComplete(strmPath, true);
                    try
                    {
                        await UpdateLiveTvChannelItemsAsync(channelEntries, ct).ConfigureAwait(false);
                    }
                    catch (Exception refreshEx)
                    {
                        Log($"Falha ao atualizar canais Live TV após o sync: {refreshEx.Message}");
                    }
                }
            }
            catch (Exception ex)
            {
                Log($"Erro no sync: {ex.Message}");
                _logger.LogError(ex, "Sync error");
                config.LastSyncError = ex.Message;
                SaveConfig(config);
                return StatusCode(500, new { error = ex.Message });
            }
        }



        private string GetDefaultStrmPath() =>
            Path.Combine(GetDataDir(), "strm");

        private static bool HasPlaylistSource(PluginConfiguration config)
        {
            return config.UseWorldStorage || !string.IsNullOrWhiteSpace(config.M3uUrl);
        }

        private string GetStrmOutputPath(PluginConfiguration config)
        {
            if (!string.IsNullOrEmpty(config.StrmOutputPath))
                return config.StrmOutputPath;
            return GetDefaultStrmPath();
        }

        private List<M3uEntry> ParseM3u(string raw, out string headerLine)
        {
            var entries = new List<M3uEntry>();
            headerLine = "#EXTM3U\n";
            var lines = raw.Split('\n');

            if (lines.Length > 0 && lines[0].StartsWith("#EXTM3U", StringComparison.Ordinal))
                headerLine = lines[0].TrimEnd('\r') + "\n";

            string? currentExtinf = null;
            var currentLines = new List<string>();

            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                if (trimmed.Length == 0) continue;

                if (trimmed.StartsWith("#EXTINF:", StringComparison.Ordinal))
                {
                    currentExtinf = line;
                    currentLines = new List<string> { line.TrimEnd('\r') + "\n" };
                }
                else if (trimmed.StartsWith('#'))
                {
                    if (currentExtinf != null)
                        currentLines.Add(line.TrimEnd('\r') + "\n");
                }
                else
                {
                    if (currentExtinf != null)
                    {
                        var cleanUrl = trimmed;
                        currentLines.Add(cleanUrl + "\n");
                        var entry = ParseEntry(currentExtinf, cleanUrl, currentLines);
                        entries.Add(entry);
                        currentExtinf = null;
                    }
                }
            }

            return entries;
        }

        private M3uEntry ParseEntry(string extinfLine, string url, List<string> rawLines)
        {
            string name = ExtractDisplayName(extinfLine);
            var tvgId = ExtractAttribute(extinfLine, "tvg-id");
            var tvgName = ExtractAttribute(extinfLine, "tvg-name");
            var groupTitle = ExtractAttribute(extinfLine, "group-title");
            var tvgLogo = ExtractAttribute(extinfLine, "tvg-logo");

            string type;
            if (IsMovieEntry(url))
                type = "Filme";
            else if (IsSeriesEntry(url))
                type = "Serie";
            else
                type = "Canal";

            if (type == "Canal")
            {
                tvgLogo = ResolveChannelLogo(tvgName, name, tvgId, tvgLogo);
            }

            string showName = name;
            string season = "Season 1";

            if (type == "Serie")
            {
                var epMatch = _epRegex.Match(name);
                if (epMatch.Success)
                {
                    showName = epMatch.Groups[1].Value.Trim();
                    season = "Season " + epMatch.Groups[2].Value;
                    var episodeTitle = epMatch.Groups[4].Value.Trim();
                    if (!string.IsNullOrEmpty(episodeTitle))
                        name = episodeTitle;
                }
            }

            return new M3uEntry
            {
                Name = name,
                Url = url,
                Type = type,
                RawLines = rawLines,
                ShowName = showName,
                Season = season,
                TvgId = tvgId,
                TvgName = tvgName,
                GroupTitle = groupTitle,
                TvgLogo = tvgLogo
            };
        }

        private static string SanitizeName(string name)
        {
            name = name.Replace(":", " - ", StringComparison.Ordinal);
            name = name.Replace("_", " - ", StringComparison.Ordinal);
            name = name.Replace("&", "e", StringComparison.Ordinal);

            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                if (c == '\uFFFD' || char.IsControl(c) || _invalidFileNameChars.Contains(c))
                {
                    sb.Append('_');
                }
                else
                {
                    sb.Append(c);
                }
            }
            return Regex.Replace(sb.ToString().TrimEnd('.', ' '), @"\s+", " ").Trim();
        }

        private static string TrimPathSegment(string value, int maxLength)
        {
            value = string.IsNullOrWhiteSpace(value) ? "_" : value.Trim();
            if (value.Length <= maxLength)
            {
                return value;
            }

            var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)))[..10];
            var prefixLength = Math.Max(1, maxLength - hash.Length - 1);
            return value[..prefixLength].TrimEnd() + "_" + hash;
        }

        private static string TruncatePathSegment(string value, int maxLength)
        {
            value = string.IsNullOrWhiteSpace(value) ? "_" : value.Trim();
            return value.Length <= maxLength ? value : value[..maxLength].TrimEnd();
        }

        private static string BuildLegacyMovieRelativePath(M3uEntry entry, int folderMaxLength, int fileMaxLength)
        {
            var name = TrimPathSegment(SanitizeName(entry.Name), folderMaxLength);
            var fileName = TrimPathSegment(SanitizeName(entry.Name), fileMaxLength);
            return Path.Combine("Filmes", name, fileName + ".strm");
        }

        private static string BuildLegacySeriesRelativePath(M3uEntry entry, int showMaxLength, int seasonMaxLength, int fileMaxLength)
        {
            var showName = TrimPathSegment(SanitizeName(entry.ShowName), showMaxLength);
            var seasonFolder = TrimPathSegment(SanitizeName(entry.Season), seasonMaxLength);
            var fileName = TrimPathSegment(SanitizeName(entry.Name), fileMaxLength);
            return Path.Combine("Series", showName, seasonFolder, fileName + ".strm");
        }

        private static string BuildEntryDedupKey(M3uEntry entry)
        {
            if (string.Equals(entry.Type, "Filme", StringComparison.OrdinalIgnoreCase))
            {
                return $"Filme|{SanitizeName(entry.Name)}";
            }

            if (string.Equals(entry.Type, "Serie", StringComparison.OrdinalIgnoreCase))
            {
                return $"Serie|{SanitizeName(entry.ShowName)}|{SanitizeName(entry.Season)}|{SanitizeName(entry.Name)}";
            }

            var stableChannelKey = !string.IsNullOrWhiteSpace(entry.TvgId)
                ? entry.TvgId!.Trim()
                : NormalizeChannelDisplayName(entry.TvgName ?? entry.Name);

            return $"Canal|{stableChannelKey}|{entry.Url.Trim()}";
        }

        private static string ExtractDisplayName(string extinfLine)
        {
            if (string.IsNullOrEmpty(extinfLine))
                return "Unknown";

            bool inQuotes = false;
            int commaIdx = -1;
            int startIdx = 0;
            if (extinfLine.StartsWith("#EXTINF:", StringComparison.OrdinalIgnoreCase))
            {
                startIdx = "#EXTINF:".Length;
            }

            for (int i = startIdx; i < extinfLine.Length; i++)
            {
                char c = extinfLine[i];
                if (c == '"')
                {
                    inQuotes = !inQuotes;
                }
                else if (c == ',' && !inQuotes)
                {
                    commaIdx = i;
                    break;
                }
            }

            string name;
            if (commaIdx >= 0)
            {
                name = extinfLine.Substring(commaIdx + 1).Trim();
            }
            else
            {
                var lastQuote = extinfLine.LastIndexOf('"');
                if (lastQuote >= 0 && lastQuote < extinfLine.Length - 1)
                {
                    name = extinfLine.Substring(lastQuote + 1).Trim();
                }
                else
                {
                    name = extinfLine;
                    if (name.StartsWith("#EXTINF:", StringComparison.OrdinalIgnoreCase))
                    {
                        var match = Regex.Match(name, @"^#EXTINF:\s*[-+]?\d+\s*");
                        if (match.Success)
                        {
                            name = name.Substring(match.Length);
                        }
                    }
                    name = name.Trim();
                }
            }

            name = CleanLeftoverAttributes(name);
            return string.IsNullOrEmpty(name) ? "Unknown" : name;
        }

        private static string CleanLeftoverAttributes(string name)
        {
            if (string.IsNullOrEmpty(name))
                return name;

            var cleaned = name;
            cleaned = Regex.Replace(cleaned, @"\b(tvg-logo|tvg-name|tvg-id|group-title|tvg-country|tvg-language|tvg-chno|logo|channel-id)\s*=\s*""[^""]*""", "", RegexOptions.IgnoreCase);
            cleaned = Regex.Replace(cleaned, @"\b(tvg-logo|tvg-name|tvg-id|group-title|tvg-country|tvg-language|tvg-chno|logo|channel-id)\s*=\s*[^\s]*", "", RegexOptions.IgnoreCase);
            cleaned = Regex.Replace(cleaned, @"\s+", " ");
            cleaned = cleaned.Trim(' ', ',', '-', '_');
            return cleaned;
        }

        private static string GetEffectiveTvgId(M3uEntry entry)
        {
            var approvedTvgId = MidiaStorageOnlineApprovedChannelMappings.TryGetEpgId(entry.TvgName, entry.Name, entry.TvgId);
            if (!string.IsNullOrWhiteSpace(approvedTvgId))
            {
                return approvedTvgId;
            }

            var mappedTvgId = MidiaStorageOnlineChannelMappings.ResolveTvgId(
                entry.TvgId,
                entry.TvgName,
                entry.GroupTitle,
                entry.Name);

            if (!string.IsNullOrWhiteSpace(mappedTvgId))
            {
                return mappedTvgId;
            }

            return BuildSyntheticXmlTvId(entry.TvgName ?? entry.GroupTitle ?? entry.Name, entry.GroupTitle ?? entry.Name, null);
        }

        private static void AppendEntryLinesWithInferredTvgId(StringBuilder builder, M3uEntry entry)
        {
            if (entry.RawLines.Count == 0)
            {
                return;
            }

            var effectiveTvgId = GetEffectiveTvgId(entry);
            var firstLine = entry.RawLines[0];
            if (firstLine.StartsWith("#EXTINF:", StringComparison.OrdinalIgnoreCase))
            {
                if (entry.Type == "Canal")
                {
                    firstLine = NormalizeChannelExtinfLine(firstLine, entry);
                }

                if (!string.IsNullOrWhiteSpace(effectiveTvgId)
                    && string.IsNullOrWhiteSpace(entry.TvgId))
                {
                    firstLine = EnsureTvgIdAttribute(firstLine, effectiveTvgId, entry.TvgName, entry.GroupTitle);
                }
            }

            builder.AppendLine(firstLine);
            for (var i = 1; i < entry.RawLines.Count; i++)
            {
                var line = entry.RawLines[i].TrimEnd('\r', '\n');
                if (i == entry.RawLines.Count - 1 && entry.Type == "Canal")
                {
                    line = MidiaStorageOnlineStreamProxy.BuildProxyUrl(line);
                }

                builder.AppendLine(line);
            }
        }

        private static string NormalizeChannelExtinfLine(string extinfLine, M3uEntry entry)
        {
            var line = extinfLine;
            line = ReplaceExtinfAttribute(line, "tvg-name", entry.TvgName ?? entry.Name);
            line = ReplaceExtinfAttribute(line, "group-title", entry.GroupTitle);
            if (string.IsNullOrWhiteSpace(entry.TvgLogo))
            {
                line = RemoveExtinfAttribute(line, "tvg-logo");
            }
            else
            {
                line = ReplaceExtinfAttribute(line, "tvg-logo", entry.TvgLogo);
            }
            line = ReplaceExtinfDisplayName(line, entry.Name);
            return line;
        }

        private static string? NormalizeChannelLogo(string? logo)
        {
            if (string.IsNullOrWhiteSpace(logo))
            {
                return null;
            }

            if (!Uri.TryCreate(logo, UriKind.Absolute, out var uri))
            {
                return null;
            }

            if (!uri.Scheme.Equals(Uri.UriSchemeHttp, StringComparison.OrdinalIgnoreCase)
                && !uri.Scheme.Equals(Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            if (uri.Host.Equals("aaa55.top", StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            return logo.Trim();
        }

        private static string? ResolveChannelLogo(string? tvgName, string? name, string? tvgId, string? tvgLogo)
        {
            var approvedLogo = MidiaStorageOnlineApprovedChannelMappings.TryGetLogoUrl(tvgName, name, tvgId);
            if (!string.IsNullOrWhiteSpace(approvedLogo))
            {
                return approvedLogo;
            }

            var workbookLogo = MidiaStorageOnlineWorkbookLogoMappings.TryGetLogoUrl(tvgName, name, tvgId);
            if (!string.IsNullOrWhiteSpace(workbookLogo))
            {
                return workbookLogo;
            }

            return NormalizeChannelLogo(tvgLogo);
        }

        private static string ReplaceExtinfDisplayName(string extinfLine, string displayName)
        {
            var commaIndex = GetExtinfDisplayNameSeparatorIndex(extinfLine);
            if (commaIndex < 0)
            {
                return $"{extinfLine},{displayName}";
            }

            return extinfLine.Substring(0, commaIndex + 1) + displayName;
        }

        private static string ReplaceExtinfAttribute(string extinfLine, string attribute, string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return extinfLine;
            }

            var sanitizedValue = value.Replace("\"", "'");
            var quotedPattern = $@"\b{Regex.Escape(attribute)}\s*=\s*""[^""]*""";
            var unquotedPattern = $@"\b{Regex.Escape(attribute)}\s*=\s*[^\s,]+";

            if (Regex.IsMatch(extinfLine, quotedPattern, RegexOptions.IgnoreCase))
            {
                return Regex.Replace(
                    extinfLine,
                    quotedPattern,
                    $"{attribute}=\"{sanitizedValue}\"",
                    RegexOptions.IgnoreCase);
            }

            if (Regex.IsMatch(extinfLine, unquotedPattern, RegexOptions.IgnoreCase))
            {
                return Regex.Replace(
                    extinfLine,
                    unquotedPattern,
                    $"{attribute}=\"{sanitizedValue}\"",
                    RegexOptions.IgnoreCase);
            }

            var insertAt = extinfLine.IndexOf(',');
            if (insertAt < 0)
            {
                insertAt = extinfLine.Length;
            }

            return extinfLine.Insert(insertAt, $" {attribute}=\"{sanitizedValue}\"");
        }

        private static string RemoveExtinfAttribute(string extinfLine, string attribute)
        {
            var quotedPattern = $@"\s+\b{Regex.Escape(attribute)}\s*=\s*""[^""]*""";
            var unquotedPattern = $@"\s+\b{Regex.Escape(attribute)}\s*=\s*[^\s,]+";

            var cleaned = Regex.Replace(extinfLine, quotedPattern, string.Empty, RegexOptions.IgnoreCase);
            cleaned = Regex.Replace(cleaned, unquotedPattern, string.Empty, RegexOptions.IgnoreCase);
            cleaned = Regex.Replace(cleaned, @"\s{2,}", " ");
            return cleaned;
        }

        private static int GetExtinfDisplayNameSeparatorIndex(string extinfLine)
        {
            if (string.IsNullOrEmpty(extinfLine))
            {
                return -1;
            }

            var inQuotes = false;
            var startIdx = extinfLine.StartsWith("#EXTINF:", StringComparison.OrdinalIgnoreCase)
                ? "#EXTINF:".Length
                : 0;

            for (var i = startIdx; i < extinfLine.Length; i++)
            {
                var c = extinfLine[i];
                if (c == '"')
                {
                    inQuotes = !inQuotes;
                }
                else if (c == ',' && !inQuotes)
                {
                    return i;
                }
            }

            return -1;
        }

        private static string EnsureTvgIdAttribute(string extinfLine, string tvgId, string? tvgName, string? groupTitle)
        {
            var quotedPattern = @"\btvg-id\s*=\s*""[^""]*""";
            var unquotedPattern = @"\btvg-id\s*=\s*[^\s,]+";

            if (Regex.IsMatch(extinfLine, quotedPattern, RegexOptions.IgnoreCase))
            {
                extinfLine = Regex.Replace(
                    extinfLine,
                    quotedPattern,
                    $"tvg-id=\"{tvgId}\"",
                    RegexOptions.IgnoreCase);
            }
            else if (Regex.IsMatch(extinfLine, unquotedPattern, RegexOptions.IgnoreCase))
            {
                extinfLine = Regex.Replace(
                    extinfLine,
                    unquotedPattern,
                    $"tvg-id=\"{tvgId}\"",
                    RegexOptions.IgnoreCase);
            }
            else
            {
                var insertAt = extinfLine.IndexOf(',');
                if (insertAt < 0)
                {
                    insertAt = extinfLine.Length;
                }

                var attrs = new StringBuilder();
                attrs.Append($" tvg-id=\"{tvgId}\"");
                if (!string.IsNullOrWhiteSpace(tvgName) && !Regex.IsMatch(extinfLine, @"\btvg-name\s*=", RegexOptions.IgnoreCase))
                {
                    attrs.Append($" tvg-name=\"{tvgName}\"");
                }
                if (!string.IsNullOrWhiteSpace(groupTitle) && !Regex.IsMatch(extinfLine, @"\bgroup-title\s*=", RegexOptions.IgnoreCase))
                {
                    attrs.Append($" group-title=\"{groupTitle}\"");
                }

                return extinfLine.Insert(insertAt, attrs.ToString());
            }

            return extinfLine;
        }

        private static string BuildSyntheticXmlTvId(string site, string siteId, string? feed)
        {
            var parts = new[] { site, siteId, feed }
                .Where(p => !string.IsNullOrWhiteSpace(p))
                .Select(p => p!.Trim().ToLowerInvariant());

            var raw = string.Join("_", parts);
            var sb = new StringBuilder(raw.Length);
            foreach (var ch in raw)
            {
                sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
            }

            var normalized = Regex.Replace(sb.ToString(), "_+", "_").Trim('_');
            return string.IsNullOrWhiteSpace(normalized) ? Guid.NewGuid().ToString("N") : normalized;
        }

        private static bool IsMovieEntry(string url)
        {
            return url.Contains("/movie/", StringComparison.OrdinalIgnoreCase);
        }

        private static bool IsSeriesEntry(string url)
        {
            return url.Contains("/series/", StringComparison.OrdinalIgnoreCase);
        }

        private static string? ExtractAttribute(string extinfLine, string attribute)
        {
            if (string.IsNullOrEmpty(extinfLine))
            {
                return null;
            }

            var match = Regex.Match(extinfLine, $@"\b{Regex.Escape(attribute)}\s*=\s*""([^""]*)""", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                return match.Groups[1].Value;
            }

            match = Regex.Match(extinfLine, $@"\b{Regex.Escape(attribute)}\s*=\s*([^\s,]+)", RegexOptions.IgnoreCase);
            return match.Success ? match.Groups[1].Value : null;
        }

        private class M3uEntry : IMidiaStorageOnlineM3uEntry
        {
            public string Name { get; set; } = "";
            public string Url { get; set; } = "";
            public string Type { get; set; } = "Canal";
            public string ShowName { get; set; } = "";
            public string Season { get; set; } = "Season 1";
            public List<string> RawLines { get; set; } = new();
            public string? TvgId { get; set; }
            public string? TvgName { get; set; }
            public string? GroupTitle { get; set; }
            public string? TvgLogo { get; set; }
        }
    }
}
