// <auto-generated />
#nullable enable
using System;
using MediaBrowser.Model.Plugins;

namespace MediaBrowser.Providers.Plugins.MidiaStorageOnline.Configuration
{
    public class PluginConfiguration : BasePluginConfiguration
    {
        public bool UseWorldStorage { get; set; }
        public string M3uUrl { get; set; } = string.Empty;
        public string? EpgUrl { get; set; }
        public string? StrmOutputPath { get; set; }
        public string OutputMode { get; set; } = "strm";
        public bool EnableAutoEpg { get; set; }
        public string AutoEpgLanguage { get; set; } = "pt";
        public int MaxLinkValidationConcurrency { get; set; }

        public string? CanaisM3uContent { get; set; }
        public string? TunerHostId { get; set; }
        public string? EpgListingProviderId { get; set; }
        public DateTime? LastSyncTime { get; set; }
        public double? LastSyncDurationSeconds { get; set; }
        public int SyncedFileCount { get; set; }
        public string? LastSyncError { get; set; }
        public DateTime? EpgLastSyncTime { get; set; }
        public string? EpgLastError { get; set; }
        public int EpgCompatibleChannelCount { get; set; }
        public int TotalChannelCount { get; set; }
    }
}
